/* ============================================================
   PREDICTO — DATA FETCHER  (API-Football / api-sports.io)
   Runs on YOUR PC (or in GitHub Actions). Pulls a WINDOW of
   fixtures (yesterday → +3 days by default) + standings, keeps
   history, and writes data.js for your website.

   You do NOT edit this file. Use set-key.bat to set your key,
   edit config.txt for leagues, then double-click run-fetch.bat.

   --- DATE WINDOW (NEW) ---
   By default this now fetches several days, not just today, so the
   website's date strip can show Yesterday / Today / Tomorrow / +2 / +3
   like NerdyTips. You can change the window in config.txt:
       DAYS_BACK=1     (how many days BEFORE today to fetch; default 1)
       DAYS_FWD=3      (how many days AFTER today to fetch;  default 3)
   Wider window = more date tabs, but longer runs + more API usage.
   ============================================================ */

const fs = require("fs");
const path = require("path");
const https = require("https");
const { buildOddsCalib } = require("./calib");
const { updateTeamProfiles, attachProfiles } = require("./team-profiles");
const engineLearning = require("./engine-learning.js");
const { buildTeamAdvanced } = require("./advanced-data");
const { attachModelCalibration } = require("./model-calibration");
const HERE = __dirname;

function readConfig() {
  const raw = fs.readFileSync(path.join(HERE, "config.txt"), "utf8");
  const cfg = { API_KEY: "", SEASON: "", LEAGUES: [] };
  for (let line of raw.split(/\r?\n/)) {
    line = line.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim().toUpperCase();
    const val = line.slice(eq + 1).trim();
    if (key === "API_KEY") cfg.API_KEY = val.replace(/['"*]/g, "").replace(/[^A-Za-z0-9\-]/g, "");
    else if (key === "SEASON") cfg.SEASON = val.replace(/[^0-9]/g, "");
    else if (key === "MAX_LEAGUES") cfg.MAX_LEAGUES = parseInt(val.replace(/[^0-9]/g,""),10) || 0;
    else if (key === "REQUEST_BUDGET") cfg.REQUEST_BUDGET = parseInt(val.replace(/[^0-9]/g,""),10) || 0;
    else if (key === "MAX_PROBES") cfg.MAX_PROBES = parseInt(val.replace(/[^0-9]/g,""),10) || 0;
    else if (key === "SLEEP_MS") cfg.SLEEP_MS = parseInt(val.replace(/[^0-9]/g,""),10) || 0;
    else if (key === "DAYS_BACK") cfg.DAYS_BACK = parseInt(val.replace(/[^0-9]/g,""),10);
    else if (key === "DAYS_FWD") cfg.DAYS_FWD = parseInt(val.replace(/[^0-9]/g,""),10);
    else if (key === "ODDS") cfg.ODDS = !/^(false|no|off|0)$/i.test(val.trim());
    else if (key === "H2H") cfg.H2H = !/^(false|no|off|0)$/i.test(val.trim());
    else if (key === "STATS") cfg.STATS = !/^(false|no|off|0)$/i.test(val.trim());
    else if (key === "LEAGUES") {
      if (/^all$/i.test(val.trim())) { cfg.LEAGUES_ALL = true; cfg.LEAGUES = []; }
      else cfg.LEAGUES = val.split(",").map(s => s.trim()).filter(Boolean).map(s => parseInt(s,10)).filter(n=>!isNaN(n));
    }
  }
  return cfg;
}

function apiGet(endpoint, key) {
  return new Promise((resolve, reject) => {
    const opts = { method:"GET", hostname:"v3.football.api-sports.io", path:endpoint, headers:{ "x-apisports-key":key } };
    const req = https.request(opts, res => {
      let body = "";
      res.on("data", d => (body += d));
      res.on("end", () => {
        if (res.statusCode === 429) { reject(new Error("RATE_LIMIT")); return; }
        try {
          const json = JSON.parse(body);
          if (json.errors && !Array.isArray(json.errors) && Object.keys(json.errors).length) {
            reject(new Error("API_ERROR: " + Object.values(json.errors).join("; "))); return;
          }
          resolve(json);
        } catch (e) { reject(new Error("Bad JSON from " + endpoint)); }
      });
    });
    req.on("error", reject);
    req.end();
  });
}

function fmtDate(d){ return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }

// ============================================================
// LEAGUE TREND DATA LAYER  (for the League Trend Banker Engine, 70-70-70)
// ------------------------------------------------------------
// Fetches every FINISHED match in a league this season and computes the REAL
// hit-rate of each market across the whole league (Section 2/4/5 of the spec).
// One fetch per league, cached for the whole run. Respects the spec's minimum
// sample (50 matches) — below that, returns null so the engine returns NO BET.
// Also assigns a league identity (Section 14) from the resulting rates.
const LEAGUE_TREND_CACHE = {};
// Tally of how the Trend engine's data source did this run — printed at the end
// so the Actions log shows, at a glance, whether Trend has data to work with.
const TREND_STATS = { okLeagues:new Set(), nullLeagues:new Set(), backfilledLeagues:new Set(), tierLeagues:new Set() };
const FINISHED_SET = new Set(["FT","AET","PEN","AWD","WO"]);
async function getLeagueTrends(leagueId, season, key, sleepMs, table, tableSize){
  if (leagueId==null || !season) return null;
  const ck = `${leagueId}|${season}`;
  if (ck in LEAGUE_TREND_CACHE) return LEAGUE_TREND_CACHE[ck];
  let result = null;
  try {
    // pull finished fixtures for the CURRENT season AND the PREVIOUS season, so
    // tier-patterns have real depth even in early/off-season when the current
    // season is too thin on its own. Games are tagged by season so we can track
    // how much of each pattern is current vs backfilled (honesty flag below).
    const prevSeason = String(parseInt(season,10) - 1);
    const fetchSeason = async (seasonId) => {
      let acc = [], page = 1, pages = 1;
      do {
        let r = null;
        // API-Football rejects &page on some single-page league queries ("The Page
        // field do not exist"), so only append it when actually paginating (page>1).
        const pageParam = page > 1 ? `&page=${page}` : "";
        for (let attempt = 0; attempt < 3; attempt++) {
          try { r = await apiGet(`/fixtures?league=${leagueId}&season=${seasonId}&status=FT-AET-PEN${pageParam}`, key); break; }
          catch (e) {
            if (String(e.message).includes("RATE_LIMIT") && attempt < 2) {
              await sleep(2000 * (attempt + 1)); // back off 2s, then 4s, then give up
              continue;
            }
            throw e; // non-rate-limit error, or out of retries -> bubble up
          }
        }
        if (r && Array.isArray(r.response)) acc = acc.concat(r.response);
        pages = (r && r.paging && r.paging.total) ? r.paging.total : 1;
        page++;
        if (page<=pages && sleepMs) await sleep(sleepMs);
      } while (page <= pages && page <= 6); // hard cap 6 pages per season
      return acc;
    };

    const curRaw = await fetchSeason(season);
    const keep = f => f && f.fixture && FINISHED_SET.has(String(f.fixture.status.short||"").toUpperCase())
      && f.goals && f.goals.home!=null && f.goals.away!=null;
    let curGames = curRaw.filter(keep).map(g => (g.__season = "current", g));

    // Only spend the extra API calls on the previous season if the current one
    // is thin. If current already has depth, don't bother backfilling.
    let prevGames = [];
    if (curGames.length < 50) {
      if (sleepMs) await sleep(sleepMs);
      const prevRaw = await fetchSeason(prevSeason);
      prevGames = prevRaw.filter(keep).map(g => (g.__season = "previous", g));
    }

    const games = curGames.concat(prevGames);
    const n = games.length;
    const nCurrent = curGames.length;
    // DIAGNOSTIC: show real counts so a null result is explainable, not mysterious.
    console.log(`    trends: league ${leagueId} season ${season} -> current=${nCurrent} prev=${prevGames.length} combined=${n} (need 30)`);
    if (n < 30) { LEAGUE_TREND_CACHE[ck] = null; return null; } // min COMBINED sample; per-bucket guards (n>=8/10/12) remain the real quality gate
    const smallSample = nCurrent < 30;              // current season alone is thin
    const backfilled = prevGames.length > 0;        // patterns lean on last season
    const currentShare = n ? Math.round((nCurrent/n)*100)/100 : 0;

    // tally every market the spec scans
    let over05=0,over15=0,over25=0,over35=0,under15=0,under25=0,under35=0,under45=0;
    let bttsYes=0,bttsNo=0, homeWin=0,awayWin=0,draw=0, homeScored=0,awayScored=0;
    let homeFTS=0,awayFTS=0, homeCS=0,awayCS=0, gib=0; // gib = goal in both halves
    let fh_over05=0, fh_under15=0, sh_over05=0, sh_over15=0, htSamp=0;
    for (const g of games){
      const h=g.goals.home, a=g.goals.away, tot=h+a;
      if(tot>=1)over05++; if(tot>=2)over15++; if(tot>=3)over25++; if(tot>=4)over35++;
      if(tot<=1)under15++; if(tot<=2)under25++; if(tot<=3)under35++; if(tot<=4)under45++;
      if(h>0&&a>0)bttsYes++; else bttsNo++;
      if(h>a)homeWin++; else if(a>h)awayWin++; else draw++;
      if(h>0)homeScored++; else homeFTS++;
      if(a>0)awayScored++; else awayFTS++;
      if(a===0)homeCS++; if(h===0)awayCS++;
      const ht=g.score&&g.score.halftime;
      if(ht&&ht.home!=null&&ht.away!=null){
        htSamp++;
        const h1=ht.home+ht.away, h2=tot-h1;
        if(h1>=1)fh_over05++; if(h1<=1)fh_under15++;
        if(h2>=1)sh_over05++; if(h2>=2)sh_over15++;
        if(h1>0&&h2>0)gib++;
      }
    }
    const R=(c,d)=> d>0 ? Math.round((c/d)*100)/100 : null;
    const rates = {
      "Over 0.5":R(over05,n),"Over 1.5":R(over15,n),"Over 2.5":R(over25,n),"Over 3.5":R(over35,n),
      "Under 1.5":R(under15,n),"Under 2.5":R(under25,n),"Under 3.5":R(under35,n),"Under 4.5":R(under45,n),
      "BTTS Yes":R(bttsYes,n),"BTTS No":R(bttsNo,n),
      "Home Win":R(homeWin,n),"Away Win":R(awayWin,n),"Draw":R(draw,n),
      "Home Team Over 0.5":R(homeScored,n),"Away Team Over 0.5":R(awayScored,n),
      "Home Team FTS":R(homeFTS,n),"Away Team FTS":R(awayFTS,n),
      "Home Clean Sheet":R(homeCS,n),"Away Clean Sheet":R(awayCS,n),
    };
    if(htSamp>=Math.min(30,n*0.5)){
      rates["First Half Over 0.5"]=R(fh_over05,htSamp);
      rates["First Half Under 1.5"]=R(fh_under15,htSamp);
      rates["Second Half Over 0.5"]=R(sh_over05,htSamp);
      rates["Second Half Over 1.5"]=R(sh_over15,htSamp);
      rates["Goal in Both Halves"]=R(gib,htSamp);
    }
    // rank markets ≥70% strongest-first, keep top 3 (Section 12/13)
    // ---- TIER-PAIRING PATTERNS (owner spec): what matches between teams of
    // specific table positions in THIS league historically produce.
    // Tiers: LDR (1st), TOP (2-4), MID, BOT (last 4). Keyed home-first so
    // "leader at home" patterns survive. Buckets need 6+ games to emit.
    let tierPatterns = null;
    if (table && tableSize) {
      const tierOf = pos => pos==null?null : pos===1?"LDR" : pos<=4?"TOP" : pos>tableSize-4?"BOT" : "MID";
      const B = {};
      // TIER buckets use CURRENT-season games ONLY: they're classified by the
      // current table, so last-season games (whose teams may sit elsewhere now,
      // or aren't in this table) would be mis-tiered. League-wide market rates
      // above safely use both seasons; tier-pairings stay current-only for
      // correctness and fill in as the season plays.
      for (const g of games){
        if (g.__season !== "current") continue;
        const hR=table[g.teams&&g.teams.home&&g.teams.home.id], aR=table[g.teams&&g.teams.away&&g.teams.away.id];
        const th=tierOf(hR&&hR.rank), ta=tierOf(aR&&aR.rank);
        if(!th||!ta) continue;
        const h=g.goals.home, a=g.goals.away, tot=h+a;
        const keys=[`${th}v${ta}`];
        if((th==="LDR"||th==="TOP")&&(ta==="LDR"||ta==="TOP")) keys.push("TOP4vTOP4");
        if(th==="LDR") keys.push("LDR_HOME");
        for(const k of keys){
          const b=B[k]=B[k]||{n:0,o15:0,o25:0,u25:0,u35:0,btts:0,homeWin:0,draw:0,awayWin:0,homeNoLoss:0};
          b.n++; if(tot>=2)b.o15++; if(tot>=3)b.o25++; if(tot<=2)b.u25++; if(tot<=3)b.u35++;
          if(h>0&&a>0)b.btts++; if(h>a)b.homeWin++; else if(h<a)b.awayWin++; else b.draw++;
          if(h>=a)b.homeNoLoss++;
        }
      }
      tierPatterns={};
      for(const [k,b] of Object.entries(B)){
        if(b.n<6) continue;
        const r2=x=>Math.round((x/b.n)*100)/100;
        tierPatterns[k]={ n:b.n, rates:{ "Over 1.5":r2(b.o15),"Over 2.5":r2(b.o25),"Under 2.5":r2(b.u25),"Under 3.5":r2(b.u35),
          "BTTS Yes":r2(b.btts),"BTTS No":r2(b.n-b.btts),"Home Win":r2(b.homeWin),"Away Win":r2(b.awayWin),
          "Draw":r2(b.draw),"Home No Loss":r2(b.homeNoLoss) } };
      }
      if(!Object.keys(tierPatterns).length) tierPatterns=null;
    }

    const ranked = Object.entries(rates)
      .filter(([,v])=>v!=null && v>=0.70)
      .sort((a,b)=>b[1]-a[1]);
    const top3 = ranked.slice(0,3).map(([m,v])=>({market:m,rate:v}));

    // league identity (Section 14) from headline rates
    const gpg = R(over25,n)!=null ? (games.reduce((s,g)=>s+g.goals.home+g.goals.away,0)/n) : null;
    const drawR = R(draw,n), homeWinR = R(homeWin,n);
    let identity="Balanced";
    if(gpg!=null){
      if(gpg>=3.0 && rates["Over 2.5"]>=0.55) identity="Goal-Friendly";
      else if(rates["Under 3.5"]!=null && rates["Under 3.5"]>=0.78) identity="Controlled";
      else if(rates["BTTS No"]!=null && rates["BTTS No"]>=0.55 && gpg<2.4) identity="Defensive";
      else if(homeWinR!=null && homeWinR>=0.50) identity="Home-Dominant";
      else if(drawR!=null && drawR>=0.32) identity="Volatile";
    }
    result = { leagueId, season, sample:n, sampleCurrent:nCurrent, currentShare, backfilled, smallSample, rates, top3, identity, tierPatterns, gpg:gpg!=null?Math.round(gpg*100)/100:null };
  } catch(e){ result = null; console.log(`    trends: league ${leagueId} THREW -> ${e.message}`); }
  LEAGUE_TREND_CACHE[ck] = result;
  return result;
}

function todayStr(){ return fmtDate(new Date()); }
// Build the list of date strings to fetch: today-back .. today+fwd (inclusive).
function buildDateWindow(back, fwd){
  const dates = [];
  const base = new Date();
  for (let off = -back; off <= fwd; off++) {
    const d = new Date(base.getFullYear(), base.getMonth(), base.getDate() + off);
    dates.push(fmtDate(d));
  }
  return dates;
}
const sleep = ms => new Promise(r=>setTimeout(r,ms));
function round1(n){ return Math.round(n*10)/10; }
function round2(n){ return (n==null||isNaN(n))?null:Math.round(n*100)/100; }
// derive points from a home/away sub-record if the API didn't supply .points
// (3 per win, 1 per draw)
function homePtsFromRow(rec){ if(!rec) return 0; const w=rec.win||0, d=rec.draw||0; return w*3 + d; }
function gdOf(rec){ if(!rec||!rec.goals) return 0; return (rec.goals.for||0)-(rec.goals.against||0); }
function cleanForm(f){ if(!f) return "—"; const s=String(f).replace(/[^WDL]/gi,"").toUpperCase(); return s?s.slice(-5):"—"; }
const FINISHED = new Set(["FT","AET","PEN"]);

(async () => {
  console.log("\n=== Predicto data fetcher (API-Football) ===\n");
  let cfg;
  try { cfg = readConfig(); }
  catch (e) { console.log("ERROR: could not read config.txt — is it next to this file?"); process.exit(1); }

  const placeholder = "PASTE_YOUR_KEY_HERE".replace(/[^A-Za-z0-9]/g,"");
  if (!cfg.API_KEY || cfg.API_KEY === placeholder) { console.log("ERROR: set your key first — double-click set-key.bat."); process.exit(1); }
  if (!cfg.LEAGUES.length && !cfg.LEAGUES_ALL) { console.log("ERROR: add league IDs in config.txt (e.g. LEAGUES=1,39,140) or set LEAGUES=ALL."); process.exit(1); }

  // Season must be a valid 4-digit year. If the secret is empty, malformed,
  // or too short (the API rejects anything under 4 chars), fall back to the
  // current year so a bad SEASON secret can never break every request.
  let season = (cfg.SEASON || "").replace(/[^0-9]/g, "");
  if (season.length !== 4) {
    const fallback = String(new Date().getFullYear());
    if (season) console.log(`SEASON "${cfg.SEASON}" is invalid — using ${fallback} instead.`);
    season = fallback;
  }
  // Delay between API calls. Default 1500ms (~40/min) — well within Ultra's
  // 450/min ceiling while staying clear of burst rejections. Pro users should
  // keep this higher (e.g. 6500). Tune with SLEEP_MS in config.txt.
  const SLEEP = (cfg.SLEEP_MS && cfg.SLEEP_MS >= 200) ? cfg.SLEEP_MS : 1500;
  // --- date window (default: yesterday .. +3) ---
  const DAYS_BACK = (cfg.DAYS_BACK != null && !isNaN(cfg.DAYS_BACK)) ? cfg.DAYS_BACK : 1;
  const DAYS_FWD  = (cfg.DAYS_FWD  != null && !isNaN(cfg.DAYS_FWD))  ? cfg.DAYS_FWD  : 3;
  const DATE_WINDOW = buildDateWindow(DAYS_BACK, DAYS_FWD);
  const today = todayStr();
  const k = cfg.API_KEY;
  console.log(`Token read: ${k.length<=8?k:k.slice(0,4)+"…"+k.slice(-4)}  (length ${k.length})`);
  console.log(`Date window: ${DATE_WINDOW[0]} … ${DATE_WINDOW[DATE_WINDOW.length-1]}  (${DATE_WINDOW.length} days)   Season: ${season}`);
  console.log(`Leagues: ${cfg.LEAGUES.length>50?cfg.LEAGUES.length+" ids":cfg.LEAGUES.join(", ")}\n`);

  const out = [];
  let requests = 0, firstError = null;

  const ALL_MODE = cfg.LEAGUES_ALL === true;
  // optional cap so a very busy day doesn't run for hours. 0 = no cap.
  const MAX_LEAGUES = cfg.MAX_LEAGUES || 0;
  const wantH2H = cfg.H2H !== false;   // full H2H on every day (per your choice)
  const wantOdds = cfg.ODDS !== false;

  // -----------------------------------------------------------------
  // STEP 1: gather fixtures for EVERY date in the window, grouped by
  // league id. Each group remembers the date + season the fixtures
  // came from, so matchDate is the REAL date (not hardcoded to today).
  // leagueGroups: [{ id, season, date, fixtures }]
  // -----------------------------------------------------------------
  const leagueGroups = [];

  if (ALL_MODE) {
    for (const date of DATE_WINDOW) {
      let gotForThisDate = false;
      for (const s of [...new Set([season, String(parseInt(season,10)-1), String(parseInt(season,10)+1)])]) {
        try {
          const r = await apiGet(`/fixtures?date=${date}&season=${s}`, cfg.API_KEY);
          requests++;
          const arr = r.response || [];
          if (arr.length) {
            const byId = {};
            for (const fx of arr) {
              const lid = fx.league && fx.league.id;
              if (!lid) continue;
              (byId[lid] = byId[lid] || []).push(fx);
            }
            for (const [lid, fxs] of Object.entries(byId)) {
              leagueGroups.push({ id: parseInt(lid,10), season: s, date, fixtures: fxs });
            }
            gotForThisDate = true;
          }
        } catch (e) {
          if (e.message === "RATE_LIMIT") { console.log("RATE LIMIT — wait a minute and run again."); }
          else if (!firstError) firstError = e.message;
        }
        await sleep(SLEEP);
        if (gotForThisDate) break; // got this date on this season, move to next date
      }
    }
    console.log(`ALL mode: ${leagueGroups.length} league-days have fixtures in the window.`);
    if (MAX_LEAGUES && leagueGroups.length > MAX_LEAGUES) {
      console.log(`Capping to ${MAX_LEAGUES} league-days (set MAX_LEAGUES in config to change).`);
      leagueGroups.length = MAX_LEAGUES;
    }
  } else {
    // LIST mode: for each league, sweep every date in the window.
    // CAPS (important for very long league lists, esp. in off-season):
    //   MAX_LEAGUES    — stop after this many DISTINCT leagues yield fixtures.
    //   MAX_PROBES     — HARD stop after this many leagues EXAMINED, whether or
    //                    not they had games. This is the off-season safety net:
    //                    without it, a 400-id list probes every empty league.
    //   REQUEST_BUDGET — hard stop if total requests cross this ceiling.
    const REQUEST_BUDGET = cfg.REQUEST_BUDGET || 6000;
    const MAX_PROBES = cfg.MAX_PROBES || 120; // leagues examined per run, max
    const leaguesWithFixtures = new Set();
    let capped = false, probes = 0;
    for (const leagueId of cfg.LEAGUES) {
      if (capped) break;
      if (requests >= REQUEST_BUDGET) {
        console.log(`Request budget reached (${requests}/${REQUEST_BUDGET}) — stopping early to protect your daily quota.`);
        break;
      }
      if (MAX_LEAGUES && leaguesWithFixtures.size >= MAX_LEAGUES) {
        console.log(`League cap reached (${MAX_LEAGUES} with fixtures) — stopping.`);
        break;
      }
      if (probes >= MAX_PROBES) {
        console.log(`Probe limit reached (${MAX_PROBES} leagues examined) — stopping. Off-season: most had no games.`);
        break;
      }
      probes++;
      const seasonsToTry = [...new Set([season, String(parseInt(season,10)-1), String(parseInt(season,10)+1)])];

      // FAST EMPTY-SKIP: probe the WHOLE date window (from..to) in ONE call per
      // season. Previously this probed only TODAY — which wrongly skipped any
      // tournament with no game today but matches later in the window (e.g. the
      // World Cup on a rest day between fixtures). Range-probing fixes that at
      // the same 1-call cost.
      const winFrom = DATE_WINDOW[0], winTo = DATE_WINDOW[DATE_WINDOW.length-1];
      let resolvedSeason = null;
      try {
        const probe = await apiGet(`/fixtures?league=${leagueId}&season=${season}&from=${winFrom}&to=${winTo}`, cfg.API_KEY);
        requests++;
        if ((probe.response || []).length) resolvedSeason = season;
      } catch (e) {
        if (e.message === "RATE_LIMIT") { console.log("RATE LIMIT — stopping early."); capped = true; break; }
        if (!firstError) firstError = e.message;
      }
      await sleep(SLEEP);

      // If the primary season was empty across the window, try the OTHER seasons
      // once each (handles season-rollover / tournament years) — 1 call per season.
      if (!resolvedSeason) {
        for (const s of seasonsToTry) {
          if (s === season) continue;
          if (requests >= REQUEST_BUDGET) { capped = true; break; }
          try {
            const probe = await apiGet(`/fixtures?league=${leagueId}&season=${s}&from=${winFrom}&to=${winTo}`, cfg.API_KEY);
            requests++;
            if ((probe.response || []).length) { resolvedSeason = s; await sleep(SLEEP); break; }
          } catch (e) { if (!firstError) firstError = e.message; }
          await sleep(SLEEP);
        }
      }

      if (capped) break;
      if (!resolvedSeason) { console.log(`League ${leagueId}: inactive (no games in window) — skipped`); continue; }

      // League is ACTIVE — now sweep the full date window on the resolved season.
      for (const date of DATE_WINDOW) {
        if (requests >= REQUEST_BUDGET) { capped = true; break; }
        try {
          const fxRes = await apiGet(`/fixtures?league=${leagueId}&season=${resolvedSeason}&date=${date}`, cfg.API_KEY);
          requests++;
          const arr = fxRes.response || [];
          if (arr.length) {
            leagueGroups.push({ id: leagueId, season: resolvedSeason, date, fixtures: arr });
            leaguesWithFixtures.add(leagueId);
          }
        } catch (e) {
          if (e.message === "RATE_LIMIT") { console.log("RATE LIMIT — stopping early."); capped = true; break; }
          if (!firstError) firstError = e.message;
        }
        await sleep(SLEEP);
      }
    }
    console.log(`LIST mode: examined ${probes} league(s), ${leaguesWithFixtures.size} had fixtures (caps: ${MAX_LEAGUES||"∞"} active / ${MAX_PROBES} probed).`);
  }

  // -----------------------------------------------------------------
  // STEP 2: standings are per league+season and DON'T change by date,
  // so fetch each (league,season) ONCE and cache it. This is the key
  // saving that keeps a multi-day window affordable.
  // -----------------------------------------------------------------
  // Parse one /standings API block into our table structure. Returns null
  // if the block has no usable rows, so the caller can try another season.
  function parseStandingsBlock(block) {
    if (!block) return null;
    const groups = block.league.standings || [];
    let table = {}, multiGroup = groups.length > 1, count = 0;
    const allRows = [];
    for (const g of groups) {
      for (const row of g) {
        const grpName = row.group || (block.league.name + (multiGroup ? " (grp)" : ""));
        table[row.team.id] = { ...row, _group: grpName };
        allRows.push(table[row.team.id]);
        count++;
      }
    }
    if (!count) return null; // empty table — let caller fall back to another season
    const tableSize = groups.length === 1 ? groups[0].length : count;

    // ---- LEAGUE BASELINE AVERAGES (no extra API calls) ----
    // Sum each team's season totals across the table to get the league's own
    // "normal": goals per game, draw rate, home-win rate. The engine uses these
    // to judge a match RELATIVE to its league instead of one global assumption.
    // Marked unreliable (and ignored) if too few games have been played, so we
    // never calibrate to a noisy small sample (early season / sparse division).
    let sumPlayed = 0, sumGoals = 0, sumDraws = 0, sumHomeWins = 0, sumHomePlayed = 0;
    for (const r of allRows) {
      const a = r.all || {};
      const p = a.played || 0;
      sumPlayed += p;
      sumGoals  += (a.goals && (a.goals.for || 0)) || 0;        // goals scored (for)
      sumGoals  += (a.goals && (a.goals.against || 0)) || 0;    // + conceded = all goals, counted twice
      sumDraws  += (a.draw || 0);
      const h = r.home || {};
      sumHomePlayed += (h.played || 0);
      sumHomeWins   += (h.win || 0);
    }
    // each game appears twice across the two teams' rows, so divide team-sums by 2
    const gamesApprox = sumPlayed / 2;
    const avgGamesPerTeam = tableSize ? sumPlayed / tableSize : 0;
    const leagueAvg = {
      goalsPerGame: gamesApprox > 0 ? Math.round((sumGoals / 2 / gamesApprox) * 100) / 100 : null,
      drawRate:     sumPlayed  > 0 ? Math.round((sumDraws / sumPlayed) * 100) / 100 : null, // draws counted per-team = per-game share
      homeWinRate:  sumHomePlayed > 0 ? Math.round((sumHomeWins / sumHomePlayed) * 100) / 100 : null,
      gamesPlayed:  Math.round(gamesApprox),
      // reliable only if teams have played a reasonable number of games
      reliable:     avgGamesPerTeam >= 5,
    };
    const byGroup = {};
    for (const r of allRows) (byGroup[r._group] = byGroup[r._group] || []).push(r);
    for (const grp of Object.values(byGroup)) {
      const homeSorted = [...grp].sort((a,b)=>{
        const ap=(a.home&&a.home.points!=null)?a.home.points:homePtsFromRow(a.home), bp=(b.home&&b.home.points!=null)?b.home.points:homePtsFromRow(b.home);
        if (bp!==ap) return bp-ap;
        return gdOf(b.home)-gdOf(a.home);
      });
      homeSorted.forEach((r,i)=>{ r._homeRank = i+1; r._homePts = (r.home&&r.home.points!=null)?r.home.points:homePtsFromRow(r.home); r._homeGames = (r.home&&r.home.played!=null)?r.home.played:null; });
      const awaySorted = [...grp].sort((a,b)=>{
        const ap=(a.away&&a.away.points!=null)?a.away.points:homePtsFromRow(a.away), bp=(b.away&&b.away.points!=null)?b.away.points:homePtsFromRow(b.away);
        if (bp!==ap) return bp-ap;
        return gdOf(b.away)-gdOf(a.away);
      });
      awaySorted.forEach((r,i)=>{ r._awayRank = i+1; r._awayPts = (r.away&&r.away.points!=null)?r.away.points:homePtsFromRow(r.away); r._awayGames = (r.away&&r.away.played!=null)?r.away.played:null; });
      grp.forEach(r=>{ r._groupSize = grp.length; });
    }
    return { table, tableSize, leagueName: block.league.name, multiGroup, leagueAvg };
  }

  // Standings don't change by date, so fetch each league ONCE and cache it.
  // We try the resolved season first, then ±1, so domestic leagues (e.g.
  // 2025/26 -> 2025) and one-off tournaments (e.g. World Cup -> 2026) both
  // find a real table from a single SEASON= setting, year-round.
  const standingsCache = {}; // key `${leagueId}` -> { table, tableSize, leagueName, multiGroup, season }
  async function getStandings(leagueId, seasonForStandings) {
    const cacheKey = `${leagueId}`;
    if (standingsCache[cacheKey]) return standingsCache[cacheKey];
    // de-duped season candidates: the one fixtures resolved to, then prev, then next
    const base = parseInt(seasonForStandings, 10);
    const seasonCandidates = [...new Set([ String(base), String(base-1), String(base+1) ])];
    let parsed = null, usedSeason = seasonForStandings;
    for (const s of seasonCandidates) {
      try {
        const stRes = await apiGet(`/standings?league=${leagueId}&season=${s}`, cfg.API_KEY); requests++;
        const block = stRes.response && stRes.response[0];
        const got = parseStandingsBlock(block);
        await sleep(SLEEP);
        if (got) { parsed = got; usedSeason = s; break; }
      } catch (e) {
        console.log(`League ${leagueId}: standings season ${s} failed (${e.message})`);
        await sleep(SLEEP);
      }
    }
    const result = parsed
      ? { ...parsed, season: usedSeason }
      : { table: {}, tableSize: 20, leagueName: `League ${leagueId}`, multiGroup: false, season: seasonForStandings };
    if (!parsed) console.log(`League ${leagueId}: no standings in seasons ${seasonCandidates.join("/")} — neutral stats`);
    standingsCache[cacheKey] = result;
    return result;
  }

  // odds are per league+date; cache by `${leagueId}|${season}|${date}`
  const oddsCache = {};
  const teamStatsCache = {}; // key `${teamId}|${leagueId}|${season}` -> stats object
  const wantStats = cfg.STATS !== false; // set STATS=false secret to disable

  // Fetch a team's finished fixtures this season and compute the CURRENT
  // streaks (of any length) at the most recent game: win / unbeaten / no-loss /
  // no-win / loss / over2.5 / under2.5. Cached per team per run. One extra
  // /fixtures call per team — the biggest per-team cost, so it's cached hard and
  // only requested for upcoming games (same as team stats).
  const teamStreakCache = {};
  async function getTeamStreaks(teamId, leagueId, season, table, cutoff, targetOpponentPPG, venueSide, gamesPlayed, tableSize){
    if(!teamId) return null;
    const ck=`${teamId}|${leagueId||"?"}|${season}|${String(cutoff||"").slice(0,10)}|${targetOpponentPPG==null?"?":Math.round(targetOpponentPPG*10)/10}|${venueSide||"?"}`;
    if(teamStreakCache[ck]!==undefined) return teamStreakCache[ck];
    let streaks=null;
    try{
      const leaguePart=leagueId?`&league=${leagueId}`:"";
      const res=await apiGet(`/fixtures?team=${teamId}${leaguePart}&season=${season}&status=FT-AET-PEN`, cfg.API_KEY); requests++;
      const cutoffMs=Date.parse(cutoff||"");
      const games=(res.response||[])
        .filter(g=>g&&g.fixture&&g.goals&&g.goals.home!=null&&g.goals.away!=null&&FINISHED.has(String(g.fixture.status.short||"").toUpperCase()))
        .filter(g=>!Number.isFinite(cutoffMs)||Date.parse(g.fixture.date)<cutoffMs)
        .sort((a,b)=>new Date(b.fixture.date)-new Date(a.fixture.date)); // most recent first
      if(games.length){
        // build a per-game result from THIS team's perspective, most-recent first
        const seq=games.map(g=>{
          const isHome=g.teams.home.id===teamId;
          const gf=isHome?g.goals.home:g.goals.away;
          const ga=isHome?g.goals.away:g.goals.home;
          // half-time result from THIS team's perspective (null if no HT data)
          const ht=g.score&&g.score.halftime;
          let htRes=null;
          if(ht&&ht.home!=null&&ht.away!=null){
            const hf=isHome?ht.home:ht.away, ha=isHome?ht.away:ht.home;
            htRes = hf>ha?"W":hf<ha?"L":"D";
          }
          // HT goals for/against from this team's perspective (null if no HT data)
          let hf=null, ha=null;
          if(ht&&ht.home!=null&&ht.away!=null){ hf=isHome?ht.home:ht.away; ha=isHome?ht.away:ht.home; }
          const oppId=isHome?g.teams.away.id:g.teams.home.id;
          const oppRow=table&&table[oppId]||null;
          const oppPlayed=oppRow&&oppRow.all&&Number(oppRow.all.played);
          const oppPoints=oppRow&&Number(oppRow.points);
          const opponentPPG=Number.isFinite(oppPlayed)&&oppPlayed>0&&Number.isFinite(oppPoints)?oppPoints/oppPlayed:null;
          const resCode=gf>ga?"W":gf<ga?"L":"D";
          return {
            res:resCode, ftRes:resCode, htRes, tot:gf+ga, gf, ga, gd:gf-ga, hf, ha,
            points:resCode==="W"?3:resCode==="D"?1:0,
            date:g.fixture.date,
            venue:isHome?"H":"A",
            opponentId:oppId,
            opponentName:isHome?g.teams.away.name:g.teams.home.name,
            opponentPos:oppRow&&oppRow.rank!=null?oppRow.rank:null,
            opponentPPG
          };
        });
        const run=pred=>{ let n=0; for(const s of seq){ if(pred(s))n++; else break; } return n; };

        // ---- HT/FT OUTCOME MATRIX (the "whole story" cross-tab) ----
        // Counts each HT→FT transition across all games with HT data, then
        // derives the behavioural rates: hold a lead, throw a lead, comeback
        // to win, comeback to draw, collapse. This is what reveals a
        // "draw-specialist" or "strong-finisher" profile the aggregates miss.
        const cell={WW:0,WD:0,WL:0,DW:0,DD:0,DL:0,LW:0,LD:0,LL:0};
        let htSamp=0;
        for(const s of seq){
          if(!s.htRes) continue;
          htSamp++;
          cell[s.htRes+s.ftRes] = (cell[s.htRes+s.ftRes]||0) + 1;
        }
        const R=(c)=> htSamp>0 ? Math.round((c/htSamp)*100)/100 : null;
        const led = cell.WW+cell.WD+cell.WL;      // games leading at HT
        const trailed = cell.LW+cell.LD+cell.LL;  // games trailing at HT
        const htft = htSamp>0 ? {
          samples: htSamp,
          cells: cell,
          holdLeadRate:  led>0 ? Math.round((cell.WW/led)*100)/100 : null,   // led→won
          throwLeadRate: led>0 ? Math.round(((cell.WD+cell.WL)/led)*100)/100 : null, // led→dropped
          comebackWinRate: trailed>0 ? Math.round((cell.LW/trailed)*100)/100 : null, // trailed→won
          comebackDrawRate: trailed>0 ? Math.round((cell.LD/trailed)*100)/100 : null,// trailed→drew
          collapseRate: trailed>0 ? Math.round((cell.LL/trailed)*100)/100 : null,    // trailed→lost
          drawFromLevelRate: (cell.DW+cell.DD+cell.DL)>0 ? Math.round((cell.DD/(cell.DW+cell.DD+cell.DL))*100)/100 : null,
          // "draw specialist" = high share of games that ended drawn from any HT state
          drawEndRate: Math.round(((cell.WD+cell.DD+cell.LD)/htSamp)*100)/100,
          // ---- extensions for the Halves engine (all among HT-sampled games) ----
          sample: htSamp, // alias of samples
          htWin: R(led), htDraw: R(cell.DW+cell.DD+cell.DL), htLoss: R(trailed),
          ftWin: R(cell.WW+cell.DW+cell.LW), ftDraw: R(cell.WD+cell.DD+cell.LD), ftLoss: R(cell.WL+cell.DL+cell.LL),
          drawToWin: (cell.DW+cell.DD+cell.DL)>0 ? Math.round((cell.DW/(cell.DW+cell.DD+cell.DL))*100)/100 : null,
          comebackRate: trailed>0 ? Math.round(((cell.LW+cell.LD)/trailed)*100)/100 : null, // trailed -> avoided defeat
          ...(function(){ // half-goal aggregates over games WITH HT data
            let n=0,fhF=0,fhA=0,shF=0,shA=0,btts=0,cs=0;
            for(const g of seq){ if(g.hf==null) continue; n++;
              fhF+=g.hf; fhA+=g.ha; shF+=(g.gf-g.hf); shA+=(g.ga-g.ha);
              if(g.hf>0&&g.ha>0) btts++; if(g.ha===0) cs++; }
            if(!n) return {};
            const r2=x=>Math.round((x/n)*100)/100;
            return { fhFor:r2(fhF), fhAg:r2(fhA), shFor:r2(shF), shAg:r2(shA),
                     fhBtts:r2(btts), htCleanSheet:r2(cs) };
          })(),
          ...(function(){ // NATIVE HT-MARKET rates — HT evidence for HT markets,
            // no stretching to full time. Over games with HT data.
            let n=0,o05=0,u15=0,weh=0,dhf=0;
            for(const g of seq){ if(g.hf==null) continue; n++;
              const fhT=g.hf+g.ha, shF=g.gf-g.hf, shA=g.ga-g.ha;
              if(fhT>=1)o05++; if(fhT<=1)u15++;
              if(g.hf>g.ha || shF>shA) weh++;                 // won either half
              if(g.hf===g.ha || g.gf===g.ga) dhf++; }          // draw at HT or FT
            if(!n) return {};
            const r=x=>Math.round((x/n)*100)/100;
            return { fhOver05:r(o05), fhUnder15:r(u15), wonEitherHalf:r(weh), drawHTorFT:r(dhf) };
          })(),
          ...(function(){ // FULL-TIME confirmation rates over ALL sampled games —
            // HT patterns are triggers; 90-minute markets (BTTS etc.) must be
            // confirmed by what actually happened at full time. Zero API cost.
            const N=seq.length; if(!N) return {};
            let b=0,cs=0,fts=0;
            for(const g of seq){ if(g.gf>0&&g.ga>0)b++; if(g.ga===0)cs++; if(g.gf===0)fts++; }
            const r=x=>Math.round((x/N)*100)/100;
            return { ftBtts:r(b), ftCS:r(cs), ftFTS:r(fts), ftSample:N };
          })(),
        } : null;

        streaks={
          win:      run(s=>s.res==="W"),
          loss:     run(s=>s.res==="L"),
          noLoss:   run(s=>s.res!=="L"),
          noWin:    run(s=>s.res!=="W"),
          noDraw:   run(s=>s.res!=="D"),
          over25:   run(s=>s.tot>=3),
          under25:  run(s=>s.tot<=2),
          // ---- market streaks (beyond wins) — all from the same fixtures,
          // zero extra API cost. Used with OPPONENT same-market confirmation. ----
          under35:       run(s=>s.tot<=3),
          over15:        run(s=>s.tot>=2),
          over35:        run(s=>s.tot>=4),
          under15:       run(s=>s.tot<=1),
          btts:          run(s=>s.gf>0&&s.ga>0),   // GG streak
          noBtts:        run(s=>!(s.gf>0&&s.ga>0)),
          scored:        run(s=>s.gf>0),
          failedToScore: run(s=>s.gf===0),
          cleanSheet:    run(s=>s.ga===0),
          concededEvery: run(s=>s.ga>0),
          teamOver15:    run(s=>s.gf>=2),          // scored 2+ streak
          sample:   seq.length,
          htft,
          advanced: buildTeamAdvanced(seq,{
            cutoff,
            targetOpponentPPG,
            venue:venueSide,
            gamesPlayed,
            tableSize
          })
        };
      }
      await sleep(SLEEP);
    }catch(e){ /* streaks optional */ }
    teamStreakCache[ck]=streaks;
    return streaks;
  }

  async function getTeamStats(teamId, leagueId, season){
    if (!wantStats || !teamId || !leagueId) return null;
    const ck = `${teamId}|${leagueId}|${season}`;
    if (teamStatsCache[ck] !== undefined) return teamStatsCache[ck];
    let stats = null;
    try {
      const res = await apiGet(`/teams/statistics?team=${teamId}&league=${leagueId}&season=${season}`, cfg.API_KEY); requests++;
      const r = res.response;
      if (r && r.fixtures) {
        const f = r.fixtures, cs = r.clean_sheet || {}, fts = r.failed_to_score || {};
        const played = (f.played && f.played.total) || 0;
        const wins = (f.wins && f.wins.total) || 0;
        const draws = (f.draws && f.draws.total) || 0;
        const loses = (f.loses && f.loses.total) || 0;
        const csTotal = cs.total || 0, ftsTotal = fts.total || 0;
        // home/away splits (used by the home-advantage engine)
        const hPlayed=(f.played&&f.played.home)||0, aPlayed=(f.played&&f.played.away)||0;
        const hWins=(f.wins&&f.wins.home)||0, aWins=(f.wins&&f.wins.away)||0;
        const hDraws=(f.draws&&f.draws.home)||0, aDraws=(f.draws&&f.draws.away)||0;

        // ---- HT/FT half-splits from goals-by-minute buckets (same response) ----
        // 1st-half buckets 0-45, 2nd-half buckets 46-90+. Gives real per-game
        // first/second-half goal tendencies for the 1H/2H markets.
        const gFor = (r.goals && r.goals.for && r.goals.for.minute) || {};
        const gAg  = (r.goals && r.goals.against && r.goals.against.minute) || {};
        const sumB = (obj,keys)=>keys.reduce((a,k)=>{ const t=obj[k]&&obj[k].total; return a+(t!=null?Number(t):0); },0);
        const FK=["0-15","16-30","31-45"], SK=["46-60","61-75","76-90","91-105"];
        const haveMinutes = Object.keys(gFor).length>0 || Object.keys(gAg).length>0;
        const f1=sumB(gFor,FK), f2=sumB(gFor,SK), a1=sumB(gAg,FK), a2=sumB(gAg,SK);

        // ---- real Over/Under hit-rates per line (same response) ----
        // r.goals.for.under_over is keyed by line ("0.5","1.5","2.5",...), each
        // { over, under }. Convert the 2.5 line to a hit-rate the spec wants.
        const ouBlock = (r.goals && r.goals.for && r.goals.for.under_over) || r.under_over || null;
        const ouRate = (line)=>{
          const cell = ouBlock && ouBlock[line];
          if (!cell) return null;
          const o = Number(cell.over)||0, u = Number(cell.under)||0;
          return (o+u)>0 ? Math.round((o/(o+u))*100)/100 : null;
        };

        stats = {
          played,
          winRate: played? wins/played : null,
          drawRate: played? draws/played : null,
          lossRate: played? loses/played : null,
          unbeatenRate: played? (wins+draws)/played : null,
          cleanSheetRate: played? csTotal/played : null,
          failedToScoreRate: played? ftsTotal/played : null,
          homeWinRate: hPlayed? hWins/hPlayed : null,
          awayWinRate: aPlayed? aWins/aPlayed : null,
          homeUnbeatenRate: hPlayed? (hWins+hDraws)/hPlayed : null,
          awayUnbeatenRate: aPlayed? (aWins+aDraws)/aPlayed : null,
          cleanSheetHome: (cs.home!=null&&hPlayed)? cs.home/hPlayed : null,
          cleanSheetAway: (cs.away!=null&&aPlayed)? cs.away/aPlayed : null,
          ftsHome: (fts.home!=null&&hPlayed)? fts.home/hPlayed : null,
          ftsAway: (fts.away!=null&&aPlayed)? fts.away/aPlayed : null,
          // NEW: HT/FT half-split per-game goal tendencies (null if no minute data)
          avg1HFor: (haveMinutes&&played)? Math.round((f1/played)*100)/100 : null,
          avg2HFor: (haveMinutes&&played)? Math.round((f2/played)*100)/100 : null,
          avg1HAgainst: (haveMinutes&&played)? Math.round((a1/played)*100)/100 : null,
          avg2HAgainst: (haveMinutes&&played)? Math.round((a2/played)*100)/100 : null,
          // NEW: real Over/Under hit-rates per line
          over15Rate: ouRate("1.5"), over25Rate: ouRate("2.5"), over35Rate: ouRate("3.5"),
        };
      }
      await sleep(SLEEP);
    } catch (e) { /* stats optional — fall back to estimates */ }
    teamStatsCache[ck] = stats;
    return stats;
  }
  async function getOdds(leagueId, seasonForStandings, date) {
    if (!wantOdds) return {};
    const cacheKey = `${leagueId}|${seasonForStandings}|${date}`;
    if (oddsCache[cacheKey]) return oddsCache[cacheKey];
    const oddsByFixture = {};
    try {
      const odRes = await apiGet(`/odds?league=${leagueId}&season=${seasonForStandings}&date=${date}`, cfg.API_KEY); requests++;
      for (const entry of (odRes.response || [])) {
        const fid = entry.fixture && entry.fixture.id;
        if (!fid) continue;
        let vals = null;
        for (const bk of (entry.bookmakers || [])) {
          const bets = bk.bets || [];
          global.__betNames = global.__betNames || new Set();
          bets.forEach(b => { if (b && b.name) global.__betNames.add(b.name); }); // debug: distinct bet names
          const findBet = re => bets.find(b => re.test(b.name || ""));
          // 1X2 / Match Winner
          const mw = findBet(/match winner|1x2|full time result/i);
          if (mw && mw.values) {
            const get = lbl => { const v = mw.values.find(x => new RegExp(lbl,"i").test(x.value)); return v ? parseFloat(v.odd) : null; };
            const h = get("^home|^1$"), d = get("^draw|^x$"), a = get("^away|^2$");
            if (h && a) {
              vals = { home: h, draw: d, away: a };
              // --- extra markets from the SAME bookmaker (free, same response) ---
              // Over/Under (values look like "Over 2.5" / "Under 2.5")
              const ou = findBet(/goals over\/under|over\/under|total goals/i);
              if (ou && ou.values) {
                const ouGet = lbl => { const v = ou.values.find(x => new RegExp(lbl,"i").test(x.value)); return v ? parseFloat(v.odd) : null; };
                vals.over15 = ouGet("over 1\\.5");  vals.under15 = ouGet("under 1\\.5");
                vals.over25 = ouGet("over 2\\.5");  vals.under25 = ouGet("under 2\\.5");
                vals.over35 = ouGet("over 3\\.5");  vals.under35 = ouGet("under 3\\.5");
              }
              // Both Teams To Score
              const btts = findBet(/both teams (to )?score|btts/i);
              if (btts && btts.values) {
                const bGet = lbl => { const v = btts.values.find(x => new RegExp(lbl,"i").test(x.value)); return v ? parseFloat(v.odd) : null; };
                vals.bttsYes = bGet("^yes"); vals.bttsNo = bGet("^no");
              }
              // Double Chance
              const dc = findBet(/double chance/i);
              if (dc && dc.values) {
                const dGet = lbl => { const v = dc.values.find(x => new RegExp(lbl,"i").test(x.value)); return v ? parseFloat(v.odd) : null; };
                vals.dc1x = dGet("home/draw|1x|^1\\/x"); vals.dc12 = dGet("home/away|12|^1\\/2"); vals.dcx2 = dGet("draw/away|x2|^x\\/2");
              }
              // --- MARKET INDICATOR ENGINE inputs (same odds response, zero extra calls) ---
              // First-Half 1X2
              const fh = findBet(/first half winner|1st half (winner|result)|half[- ]?time result|ht result/i);
              if (fh && fh.values) {
                const fGet = lbl => { const v = fh.values.find(x => new RegExp(lbl,"i").test(x.value)); return v ? parseFloat(v.odd) : null; };
                vals.fhHome = fGet("^home|^1$"); vals.fhDraw = fGet("^draw|^x$"); vals.fhAway = fGet("^away|^2$");
              }
              // First-Half Over/Under
              const fhou = findBet(/(first|1st) half.*over\/under|over\/under.*(first|1st) half|goals.*(first|1st) half/i);
              if (fhou && fhou.values) {
                const foGet = lbl => { const v = fhou.values.find(x => new RegExp(lbl,"i").test(x.value)); return v ? parseFloat(v.odd) : null; };
                vals.fhOver05 = foGet("over 0\\.5"); vals.fhOver15 = foGet("over 1\\.5"); vals.fhUnder15 = foGet("under 1\\.5");
              }
              // GG / NG spec aliases (BTTS prices already parsed above)
              if (vals.bttsYes != null) vals.gg = vals.bttsYes;
              if (vals.bttsNo  != null) vals.ng = vals.bttsNo;
              // GG2+ (both-teams-score-2+ / multigoal family) — defensive multi-pattern;
              // stays null if this book doesn't price it, engine must treat null as "no signal"
              const g2 = findBet(/both teams.*score.*2|gg\s*2|multi ?goals?/i);
              if (g2 && g2.values) {
                const gGet = lbl => { const v = g2.values.find(x => new RegExp(lbl,"i").test(x.value)); return v ? parseFloat(v.odd) : null; };
                vals.gg2 = gGet("^yes$|^2\\+$|2\\+ goals");
              }
              break;
            }
          }
        }
        if (vals) oddsByFixture[fid] = vals;
      }
      await sleep(SLEEP);
    } catch (e) { /* odds optional — ignore failures */ }
    oddsCache[cacheKey] = oddsByFixture;
    return oddsByFixture;
  }

  // -----------------------------------------------------------------
  // STEP 3: process every league-day group: standings (cached) + odds
  // (cached) + per-match H2H, then build the match record. matchDate is
  // grp.date — the REAL date of the fixture.
  // -----------------------------------------------------------------
  for (const grp of leagueGroups) {
    const leagueId = grp.id;
    const seasonForStandings = grp.season;
    const date = grp.date;
    const fixtures = grp.fixtures;

    const standings = await getStandings(leagueId, seasonForStandings);
    const { table, tableSize, multiGroup } = standings;
    const leagueAvg = standings.leagueAvg || null;
    let leagueName = standings.leagueName;
    let leagueCountry = null, leagueFlag = null;
    if (fixtures[0].league) {
      if (fixtures[0].league.name) leagueName = fixtures[0].league.name;
      // country + flag image URL come free in the fixture's league block
      leagueCountry = fixtures[0].league.country || null;
      leagueFlag = fixtures[0].league.flag || null;
    }

    const oddsByFixture = await getOdds(leagueId, seasonForStandings, date);

    // League Trend data (70-70-70 engine): real league-wide market hit-rates,
    // fetched once per league and cached. null if <50 matches or fetch failed.
    let leagueTrends = null;
    try { leagueTrends = await getLeagueTrends(leagueId, seasonForStandings, cfg.API_KEY, SLEEP, table, tableSize); requests++;
      if(!leagueTrends){ TREND_STATS.nullLeagues.add(leagueId); console.log(`    trends: league ${leagueId} -> null (combined sample <30 or empty response)`); }
      else { TREND_STATS.okLeagues.add(leagueId); if(leagueTrends.backfilled) TREND_STATS.backfilledLeagues.add(leagueId); if(leagueTrends.tierPatterns) TREND_STATS.tierLeagues.add(leagueId); } }
    catch(e){ leagueTrends = null; TREND_STATS.nullLeagues.add(leagueId); console.log(`    trends: league ${leagueId} FAILED -> ${e.message}`); }

    for (const fx of fixtures) {
      const st = fx.fixture.status.short;
      const H = table[fx.teams.home.id] || {}, A = table[fx.teams.away.id] || {};
      const hHome = H.home || {}, aAway = A.away || {};
      const played = FINISHED.has(st);
      const homeGroup = H._group || null, awayGroup = A._group || null;
      const sameGroup = !!(homeGroup && awayGroup && homeGroup === awayGroup);
      const roundName = (fx.league && fx.league.round) ? String(fx.league.round) : "";
      const isKnockout = /final|semi|quarter|round of|knockout|1\/|play-?off/i.test(roundName);

      // ---- HEAD-TO-HEAD: full H2H on every day in the window (your choice) ----
      let h2h = null;
      if (wantH2H) {
        try {
          const hid = fx.teams.home.id, aid = fx.teams.away.id;
          const hr = await apiGet(`/fixtures/headtohead?h2h=${hid}-${aid}&last=6`, cfg.API_KEY); requests++;
          const games = (hr.response || []).filter(g => FINISHED.has(g.fixture.status.short));
          if (games.length) {
            let homeWins=0, awayWins=0, draws=0, over25=0, bttsCount=0;
            // half-time goal aggregation (API-Football returns score.halftime).
            // 1H goals = HT total; 2H goals = FT total minus HT total.
            let htSum=0, ftSum=0, htSamples=0;
            const recent = [];
            for (const g of games) {
              const gh=g.goals.home, ga=g.goals.away;
              if (gh==null||ga==null) continue;
              let res;
              if (gh===ga) { draws++; res="D"; }
              else {
                const winId = gh>ga ? g.teams.home.id : g.teams.away.id;
                if (winId===hid) { homeWins++; res="H"; } else if (winId===aid) { awayWins++; res="A"; } else res="?";
              }
              if (gh+ga>=3) over25++;
              if (gh>0 && ga>0) bttsCount++;
              // half-time goals for this fixture
              const ht = g.score && g.score.halftime;
              if (ht && ht.home!=null && ht.away!=null) {
                htSum += (ht.home + ht.away);
                ftSum += (gh + ga);
                htSamples++;
              }
              recent.push({ date:(g.fixture.date||"").slice(0,10),
                ht:g.teams.home.name, at:g.teams.away.name, hg:gh, ag:ga, res });
            }
            h2h = { played:games.length, homeWins, awayWins, draws, over25, bttsCount, recent:recent.slice(0,5) };
            // average 1st-half and 2nd-half goals across the H2H sample (real data).
            if (htSamples > 0) {
              h2h.avg1H = Math.round((htSum / htSamples) * 100) / 100;
              h2h.avg2H = Math.round(((ftSum - htSum) / htSamples) * 100) / 100;
              h2h.htSamples = htSamples;
            }
          }
          await sleep(SLEEP);
        } catch (e) { /* h2h optional */ }
      }

      // REAL team stats (cached per team per run) — only fetch for games not
      // already finished, to contain cost (no point fetching for settled games).
      let homeStats = null, awayStats = null;
      let homeStreaks = null, awayStreaks = null;
      if (wantStats && st !== "FT" && st !== "AET" && st !== "PEN") {
        const hid = fx.teams.home.id, aid = fx.teams.away.id;
        homeStats = await getTeamStats(hid, leagueId, seasonForStandings);
        awayStats = await getTeamStats(aid, leagueId, seasonForStandings);
        const hPlayed=H&&H.all&&Number(H.all.played), aPlayed=A&&A.all&&Number(A.all.played);
        const hPPG=Number.isFinite(hPlayed)&&hPlayed>0?Number(H.points||0)/hPlayed:null;
        const aPPG=Number.isFinite(aPlayed)&&aPlayed>0?Number(A.points||0)/aPlayed:null;
        homeStreaks = await getTeamStreaks(hid,leagueId,seasonForStandings,table,fx.fixture.date,aPPG,"H",hPlayed,tableSize);
        awayStreaks = await getTeamStreaks(aid,leagueId,seasonForStandings,table,fx.fixture.date,hPPG,"A",aPlayed,tableSize);
      }

      const __ht = fx.score && fx.score.halftime;
      out.push({
        id: (fx.fixture && fx.fixture.id) || null, // stable fixture id — slips/community reference matches by this
        home: fx.teams.home.name, away: fx.teams.away.name, league: leagueName, leagueId: leagueId,
        season: seasonForStandings,
        homeTeamId: fx.teams.home.id, awayTeamId: fx.teams.away.id,
        htHome: (__ht && __ht.home!=null) ? __ht.home : null,  // half-time score —
        htAway: (__ht && __ht.away!=null) ? __ht.away : null,  // settles HT markets
        homeLogo: (fx.teams.home && fx.teams.home.logo) || null,
        awayLogo: (fx.teams.away && fx.teams.away.logo) || null,
        country: leagueCountry, flag: leagueFlag,
        status: st, kickoff: fx.fixture.date || null, matchDate: date,
        homeGoals: (fx.goals && fx.goals.home != null) ? fx.goals.home : null,
        awayGoals: (fx.goals && fx.goals.away != null) ? fx.goals.away : null,
        homePos: H.rank ?? null, awayPos: A.rank ?? null, tableSize,
        homePts: H.points ?? 0, awayPts: A.points ?? 0,
        homeGD: H.goalsDiff ?? 0, awayGD: A.goalsDiff ?? 0,
        homeForm: cleanForm(H.form), awayForm: cleanForm(A.form),
        homeScoredAtHome: round1(hHome.played ? hHome.goals.for/hHome.played : 1.3),
        homeConcededAtHome: round1(hHome.played ? hHome.goals.against/hHome.played : 1.1),
        awayScoredAway: round1(aAway.played ? aAway.goals.for/aAway.played : 1.0),
        awayConcededAway: round1(aAway.played ? aAway.goals.against/aAway.played : 1.4),
        homeVenueRank: H._homeRank ?? null, awayVenueRank: A._awayRank ?? null,
        homeVenuePts: H._homePts ?? null, awayVenuePts: A._awayPts ?? null,
        homeVenueGames: H._homeGames ?? null, awayVenueGames: A._awayGames ?? null,
        venueTableSize: H._groupSize ?? A._groupSize ?? tableSize,
        leagueAvg,  // per-league baseline averages for engine calibration
        leagueTrends,  // 70-70-70 engine: real league-wide market hit-rates, top-3, identity
        // REAL stats (null when unavailable -> engines fall back to estimates)
        homeWinRate: homeStats ? round2(homeStats.homeWinRate ?? homeStats.winRate) : null,
        awayWinRate: awayStats ? round2(awayStats.awayWinRate ?? awayStats.winRate) : null,
        homeUnbeatenRate: homeStats ? round2(homeStats.homeUnbeatenRate ?? homeStats.unbeatenRate) : null,
        awayUnbeatenRate: awayStats ? round2(awayStats.awayUnbeatenRate ?? awayStats.unbeatenRate) : null,
        homeCleanSheetRate: homeStats ? round2(homeStats.cleanSheetHome ?? homeStats.cleanSheetRate) : null,
        awayCleanSheetRate: awayStats ? round2(awayStats.cleanSheetAway ?? awayStats.cleanSheetRate) : null,
        homeFailedToScoreRate: homeStats ? round2(homeStats.ftsHome ?? homeStats.failedToScoreRate) : null,
        awayFailedToScoreRate: awayStats ? round2(awayStats.ftsAway ?? awayStats.failedToScoreRate) : null,
        // HT/FT half-split goal tendencies (real, from goals-by-minute)
        home1HFor: homeStats ? homeStats.avg1HFor : null,
        home2HFor: homeStats ? homeStats.avg2HFor : null,
        home1HAgainst: homeStats ? homeStats.avg1HAgainst : null,
        home2HAgainst: homeStats ? homeStats.avg2HAgainst : null,
        away1HFor: awayStats ? awayStats.avg1HFor : null,
        away2HFor: awayStats ? awayStats.avg2HFor : null,
        away1HAgainst: awayStats ? awayStats.avg1HAgainst : null,
        away2HAgainst: awayStats ? awayStats.avg2HAgainst : null,
        // real Over/Under hit-rates per line
        homeOver25Rate: homeStats ? homeStats.over25Rate : null,
        awayOver25Rate: awayStats ? awayStats.over25Rate : null,
        homeOver15Rate: homeStats ? homeStats.over15Rate : null,
        awayOver15Rate: awayStats ? awayStats.over15Rate : null,
        homeOver35Rate: homeStats ? homeStats.over35Rate : null,
        awayOver35Rate: awayStats ? awayStats.over35Rate : null,
        statsReal: !!(homeStats || awayStats),
        // real streaks of any length (from full season fixture history)
        homeStreaks, awayStreaks,

        // ---- ADVANCED DERIVED DATA (real chronological league fixtures) ----
        homeRecent10PPG: homeStreaks&&homeStreaks.advanced?homeStreaks.advanced.recent10PPG:null,
        awayRecent10PPG: awayStreaks&&awayStreaks.advanced?awayStreaks.advanced.recent10PPG:null,
        homeRecent10Form: homeStreaks&&homeStreaks.advanced?homeStreaks.advanced.recent10Form:null,
        awayRecent10Form: awayStreaks&&awayStreaks.advanced?awayStreaks.advanced.recent10Form:null,
        homeOpponentAvgPPG: homeStreaks&&homeStreaks.advanced?homeStreaks.advanced.opponentAvgPPG:null,
        awayOpponentAvgPPG: awayStreaks&&awayStreaks.advanced?awayStreaks.advanced.opponentAvgPPG:null,
        homeScheduleStrengthPPG: homeStreaks&&homeStreaks.advanced?homeStreaks.advanced.opponentAvgPPG:null,
        awayScheduleStrengthPPG: awayStreaks&&awayStreaks.advanced?awayStreaks.advanced.opponentAvgPPG:null,
        homeSimilarOpponentPPG: homeStreaks&&homeStreaks.advanced?homeStreaks.advanced.similarOpponentPPG:null,
        awaySimilarOpponentPPG: awayStreaks&&awayStreaks.advanced?awayStreaks.advanced.similarOpponentPPG:null,
        homeRestDays: homeStreaks&&homeStreaks.advanced?homeStreaks.advanced.restDays:null,
        awayRestDays: awayStreaks&&awayStreaks.advanced?awayStreaks.advanced.restDays:null,
        homeSplitBlockDifference: homeStreaks&&homeStreaks.advanced?homeStreaks.advanced.splitBlockDifference:null,
        awaySplitBlockDifference: awayStreaks&&awayStreaks.advanced?awayStreaks.advanced.splitBlockDifference:null,
        recent10:{
          home:homeStreaks&&homeStreaks.advanced?{ppg:homeStreaks.advanced.recent10PPG,form:homeStreaks.advanced.recent10Form,sample:homeStreaks.advanced.samples.recent10}:null,
          away:awayStreaks&&awayStreaks.advanced?{ppg:awayStreaks.advanced.recent10PPG,form:awayStreaks.advanced.recent10Form,sample:awayStreaks.advanced.samples.recent10}:null
        },
        opponentStrength:{
          home:homeStreaks&&homeStreaks.advanced?{avgPPG:homeStreaks.advanced.opponentAvgPPG,sample:homeStreaks.advanced.samples.opponentStrength}:null,
          away:awayStreaks&&awayStreaks.advanced?{avgPPG:awayStreaks.advanced.opponentAvgPPG,sample:awayStreaks.advanced.samples.opponentStrength}:null
        },
        similarOpponents:{
          home:homeStreaks&&homeStreaks.advanced?{ppg:homeStreaks.advanced.similarOpponentPPG,sample:homeStreaks.advanced.similarOpponentSample,band:homeStreaks.advanced.similarOpponentBand}:null,
          away:awayStreaks&&awayStreaks.advanced?{ppg:awayStreaks.advanced.similarOpponentPPG,sample:awayStreaks.advanced.similarOpponentSample,band:awayStreaks.advanced.similarOpponentBand}:null
        },
        rest:{
          home:homeStreaks&&homeStreaks.advanced?{days:homeStreaks.advanced.restDays}:null,
          away:awayStreaks&&awayStreaks.advanced?{days:awayStreaks.advanced.restDays}:null
        },
        fixtureDensity:{
          home:homeStreaks&&homeStreaks.advanced?homeStreaks.advanced.fixtureDensity:null,
          away:awayStreaks&&awayStreaks.advanced?awayStreaks.advanced.fixtureDensity:null
        },
        splitStability:{
          home:homeStreaks&&homeStreaks.advanced?{difference:homeStreaks.advanced.splitBlockDifference}:null,
          away:awayStreaks&&awayStreaks.advanced?{difference:awayStreaks.advanced.splitBlockDifference}:null
        },
        momentum:{
          home:homeStreaks&&homeStreaks.advanced?homeStreaks.advanced.momentum:null,
          away:awayStreaks&&awayStreaks.advanced?awayStreaks.advanced.momentum:null
        },
        seasonPhase:(homeStreaks&&homeStreaks.advanced&&homeStreaks.advanced.seasonPhase)||
                    (awayStreaks&&awayStreaks.advanced&&awayStreaks.advanced.seasonPhase)||null,
        advancedDataMeta:{
          source:"API-Football chronological league fixtures + current table strength",
          home:homeStreaks&&homeStreaks.advanced?homeStreaks.advanced.samples:null,
          away:awayStreaks&&awayStreaks.advanced?awayStreaks.advanced.samples:null
        },

        sameGroup, isKnockout,
        isTournament: multiGroup || isKnockout,
        round: roundName || null,
        odds: oddsByFixture[fx.fixture.id] || null,
        h2h,
      });
      console.log(`  + [${date}] ${fx.teams.home.name} vs ${fx.teams.away.name}${played?` (${fx.goals.home}-${fx.goals.away} FT)`:""}  [${leagueName}]${isKnockout?" (KO)":""}`);
    }
    await sleep(SLEEP);
  }

  if (!out.length) {
    if (firstError) {
      console.log("\nNo matches saved. First issue: " + firstError);
      if (firstError.includes("season")) console.log("If it mentions the season, your plan may not cover it. Pro unlocks current seasons.");
    } else {
      console.log("\nNo fixtures in the window in your leagues (off-season is normal in summer).");
      console.log("The World Cup is league ID 1 — make sure it's in config.txt.");
    }
    console.log("Leaving your existing data.js untouched (not overwriting with empty).\n");
    return;
  }

  // -----------------------------------------------------------------
  // MERGE: keep any saved days that are OUTSIDE this run's window
  // untouched, and replace every day that IS in the window with the
  // freshly fetched data. (Previously this only replaced 'today'.)
  // -----------------------------------------------------------------
  let existing = [];
  try {
    const prev = fs.readFileSync(path.join(HERE, "data.js"), "utf8");
    const m = prev.match(/window\.MATCHES\s*=\s*(\[[\s\S]*\]);?\s*$/);
    if (m) existing = JSON.parse(m[1]);
  } catch (e) {}
  const windowSet = new Set(DATE_WINDOW);
  const kept = existing.filter(x => x.matchDate && !windowSet.has(x.matchDate));
  const merged = kept.concat(out);
  merged.sort((a,b)=>{ if(a.matchDate!==b.matchDate) return (b.matchDate||"").localeCompare(a.matchDate||""); return (a.kickoff||"").localeCompare(b.kickoff||""); });

  // ---- ODDS CALIBRATION LEDGER (owner spec): how markets PERFORMED at each
  // price band in each league, mined from the board's OWN saved history —
  // every finished match whose pre-match odds we captured. Self-accumulating:
  // gets sharper every day the board runs. Attached to every match so engines
  // can sanity-check a pick's price against this league's real hit rate.
  // Shared builder (calib.js) — same logic, now single-source so fetch-scores
  // rebuilds the SAME ledger and can never wipe it again.
  {
    const r = buildOddsCalib(merged);
    console.log(`Odds calibration: ${r.leagues} league ledgers built, attached to ${r.attached} matches.`);
    // Team-profile ledger: accumulate per-team evidence (season seed + settled
    // rows + xG where measured), then attach each match's two profiles so the
    // browser engine can read them from data.js (same pattern as oddsCalib).
    const tp = updateTeamProfiles(merged);
    const ta = attachProfiles(merged);
    console.log(`Team profiles: ${tp.teams} teams in ledger (+${tp.rowsAdded} rows, ${tp.settledWithXg} with xG); attached to ${ta.attached} match-sides.`);
    const mc = attachModelCalibration(merged,{writeLedger:true});
    console.log(`Model calibration: ${mc.groups} validated groups; attached ${mc.attached} market intervals to ${mc.matches} matches.`);
  }

  fs.writeFileSync(path.join(HERE, "data.js"),
    "/* AUTO-GENERATED by fetch-data.js on " + new Date().toLocaleString() + " — do not edit by hand. */\n\n" +
    "window.DATA_UPDATED = \"" + new Date().toISOString() + "\";\n" +
    "window.MATCHES = " + JSON.stringify(merged, null, 2) + ";\n", "utf8");

  try {
    const lr = engineLearning.runBuild();
    console.log(`Engine learning: ${lr.ledger.summary.reviewedLosses} reviewed losses; ${lr.attached} upcoming contexts attached.`);
  } catch(e) { console.log("Engine learning refresh skipped:", e.message); }

  const finishedCount = out.filter(x=>x.homeGoals!=null).length;
  const daysCovered = [...new Set(out.map(x=>x.matchDate))].sort();
  console.log(`\nDone. Window: ${out.length} match(es) across ${daysCovered.length} day(s) [${daysCovered.join(", ")}] (${finishedCount} finished). ${requests} requests used.`);
  console.log(`Board now holds ${merged.length} match(es) across all saved days.`);
  console.log(`Trend data: ${TREND_STATS.okLeagues.size} league(s) qualified (${TREND_STATS.backfilledLeagues.size} used last-season backfill, ${TREND_STATS.tierLeagues.size} have tier-patterns); ${TREND_STATS.nullLeagues.size} league(s) had too few games. If qualified = 0, the Trend engine will show No Bet everywhere — that's the calendar, not a bug.`);
  if (global.__betNames && global.__betNames.size) console.log("DEBUG distinct odds bet names seen: " + [...global.__betNames].sort().join(" | "));
  console.log("Next: commit data.js (the workflow deploys it), or for local runs upload your folder.\n");
})();
