/* ============================================================
   PREDICTO — DATA FETCHER  (API-Football / api-sports.io)
   Runs on YOUR PC (or in GitHub Actions). Pulls a WINDOW of
   fixtures (yesterday → +3 days by default) + standings, keeps
   history, and writes data.js for your website.

   You do NOT edit this file. Use set-key.bat to set your key,
   edit config.txt for leagues, then double-click run-fetch.bat.

   --- DATE WINDOW (NEW) ---
   By default this now fetches several days, not just today, so the
   website's date strip can show Yesterday / Today / Tomorrow / +2 / +3
   like NerdyTips. You can change the window in config.txt:
       DAYS_BACK=1     (how many days BEFORE today to fetch; default 1)
       DAYS_FWD=3      (how many days AFTER today to fetch;  default 3)
   Wider window = more date tabs, but longer runs + more API usage.
   ============================================================ */

const fs = require("fs");
const path = require("path");
const https = require("https");
const HERE = __dirname;

function readConfig() {
  const raw = fs.readFileSync(path.join(HERE, "config.txt"), "utf8");
  const cfg = { API_KEY: "", SEASON: "", LEAGUES: [] };
  for (let line of raw.split(/\r?\n/)) {
    line = line.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim().toUpperCase();
    const val = line.slice(eq + 1).trim();
    if (key === "API_KEY") cfg.API_KEY = val.replace(/['"*]/g, "").replace(/[^A-Za-z0-9\-]/g, "");
    else if (key === "SEASON") cfg.SEASON = val.replace(/[^0-9]/g, "");
    else if (key === "MAX_LEAGUES") cfg.MAX_LEAGUES = parseInt(val.replace(/[^0-9]/g,""),10) || 0;
    else if (key === "REQUEST_BUDGET") cfg.REQUEST_BUDGET = parseInt(val.replace(/[^0-9]/g,""),10) || 0;
    else if (key === "MAX_PROBES") cfg.MAX_PROBES = parseInt(val.replace(/[^0-9]/g,""),10) || 0;
    else if (key === "SLEEP_MS") cfg.SLEEP_MS = parseInt(val.replace(/[^0-9]/g,""),10) || 0;
    else if (key === "DAYS_BACK") cfg.DAYS_BACK = parseInt(val.replace(/[^0-9]/g,""),10);
    else if (key === "DAYS_FWD") cfg.DAYS_FWD = parseInt(val.replace(/[^0-9]/g,""),10);
    else if (key === "ODDS") cfg.ODDS = !/^(false|no|off|0)$/i.test(val.trim());
    else if (key === "H2H") cfg.H2H = !/^(false|no|off|0)$/i.test(val.trim());
    else if (key === "STATS") cfg.STATS = !/^(false|no|off|0)$/i.test(val.trim());
    else if (key === "LEAGUES") {
      if (/^all$/i.test(val.trim())) { cfg.LEAGUES_ALL = true; cfg.LEAGUES = []; }
      else cfg.LEAGUES = val.split(",").map(s => s.trim()).filter(Boolean).map(s => parseInt(s,10)).filter(n=>!isNaN(n));
    }
  }
  return cfg;
}

function apiGet(endpoint, key) {
  return new Promise((resolve, reject) => {
    const opts = { method:"GET", hostname:"v3.football.api-sports.io", path:endpoint, headers:{ "x-apisports-key":key } };
    const req = https.request(opts, res => {
      let body = "";
      res.on("data", d => (body += d));
      res.on("end", () => {
        if (res.statusCode === 429) { reject(new Error("RATE_LIMIT")); return; }
        try {
          const json = JSON.parse(body);
          if (json.errors && !Array.isArray(json.errors) && Object.keys(json.errors).length) {
            reject(new Error("API_ERROR: " + Object.values(json.errors).join("; "))); return;
          }
          resolve(json);
        } catch (e) { reject(new Error("Bad JSON from " + endpoint)); }
      });
    });
    req.on("error", reject);
    req.end();
  });
}

function fmtDate(d){ return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
function todayStr(){ return fmtDate(new Date()); }
// Build the list of date strings to fetch: today-back .. today+fwd (inclusive).
function buildDateWindow(back, fwd){
  const dates = [];
  const base = new Date();
  for (let off = -back; off <= fwd; off++) {
    const d = new Date(base.getFullYear(), base.getMonth(), base.getDate() + off);
    dates.push(fmtDate(d));
  }
  return dates;
}
const sleep = ms => new Promise(r=>setTimeout(r,ms));
function round1(n){ return Math.round(n*10)/10; }
function round2(n){ return (n==null||isNaN(n))?null:Math.round(n*100)/100; }
// derive points from a home/away sub-record if the API didn't supply .points
// (3 per win, 1 per draw)
function homePtsFromRow(rec){ if(!rec) return 0; const w=rec.win||0, d=rec.draw||0; return w*3 + d; }
function gdOf(rec){ if(!rec||!rec.goals) return 0; return (rec.goals.for||0)-(rec.goals.against||0); }
function cleanForm(f){ if(!f) return "—"; const s=String(f).replace(/[^WDL]/gi,"").toUpperCase(); return s?s.slice(-5):"—"; }
const FINISHED = new Set(["FT","AET","PEN"]);

(async () => {
  console.log("\n=== Predicto data fetcher (API-Football) ===\n");
  let cfg;
  try { cfg = readConfig(); }
  catch (e) { console.log("ERROR: could not read config.txt — is it next to this file?"); process.exit(1); }

  const placeholder = "PASTE_YOUR_KEY_HERE".replace(/[^A-Za-z0-9]/g,"");
  if (!cfg.API_KEY || cfg.API_KEY === placeholder) { console.log("ERROR: set your key first — double-click set-key.bat."); process.exit(1); }
  if (!cfg.LEAGUES.length && !cfg.LEAGUES_ALL) { console.log("ERROR: add league IDs in config.txt (e.g. LEAGUES=1,39,140) or set LEAGUES=ALL."); process.exit(1); }

  // Season must be a valid 4-digit year. If the secret is empty, malformed,
  // or too short (the API rejects anything under 4 chars), fall back to the
  // current year so a bad SEASON secret can never break every request.
  let season = (cfg.SEASON || "").replace(/[^0-9]/g, "");
  if (season.length !== 4) {
    const fallback = String(new Date().getFullYear());
    if (season) console.log(`SEASON "${cfg.SEASON}" is invalid — using ${fallback} instead.`);
    season = fallback;
  }
  // Delay between API calls. Default 1500ms (~40/min) — well within Ultra's
  // 450/min ceiling while staying clear of burst rejections. Pro users should
  // keep this higher (e.g. 6500). Tune with SLEEP_MS in config.txt.
  const SLEEP = (cfg.SLEEP_MS && cfg.SLEEP_MS >= 200) ? cfg.SLEEP_MS : 1500;
  // --- date window (default: yesterday .. +3) ---
  const DAYS_BACK = (cfg.DAYS_BACK != null && !isNaN(cfg.DAYS_BACK)) ? cfg.DAYS_BACK : 1;
  const DAYS_FWD  = (cfg.DAYS_FWD  != null && !isNaN(cfg.DAYS_FWD))  ? cfg.DAYS_FWD  : 3;
  const DATE_WINDOW = buildDateWindow(DAYS_BACK, DAYS_FWD);
  const today = todayStr();
  const k = cfg.API_KEY;
  console.log(`Token read: ${k.length<=8?k:k.slice(0,4)+"…"+k.slice(-4)}  (length ${k.length})`);
  console.log(`Date window: ${DATE_WINDOW[0]} … ${DATE_WINDOW[DATE_WINDOW.length-1]}  (${DATE_WINDOW.length} days)   Season: ${season}`);
  console.log(`Leagues: ${cfg.LEAGUES.length>50?cfg.LEAGUES.length+" ids":cfg.LEAGUES.join(", ")}\n`);

  const out = [];
  let requests = 0, firstError = null;

  const ALL_MODE = cfg.LEAGUES_ALL === true;
  // optional cap so a very busy day doesn't run for hours. 0 = no cap.
  const MAX_LEAGUES = cfg.MAX_LEAGUES || 0;
  const wantH2H = cfg.H2H !== false;   // full H2H on every day (per your choice)
  const wantOdds = cfg.ODDS !== false;

  // -----------------------------------------------------------------
  // STEP 1: gather fixtures for EVERY date in the window, grouped by
  // league id. Each group remembers the date + season the fixtures
  // came from, so matchDate is the REAL date (not hardcoded to today).
  // leagueGroups: [{ id, season, date, fixtures }]
  // -----------------------------------------------------------------
  const leagueGroups = [];

  if (ALL_MODE) {
    for (const date of DATE_WINDOW) {
      let gotForThisDate = false;
      for (const s of [...new Set([season, String(parseInt(season,10)-1), String(parseInt(season,10)+1)])]) {
        try {
          const r = await apiGet(`/fixtures?date=${date}&season=${s}`, cfg.API_KEY);
          requests++;
          const arr = r.response || [];
          if (arr.length) {
            const byId = {};
            for (const fx of arr) {
              const lid = fx.league && fx.league.id;
              if (!lid) continue;
              (byId[lid] = byId[lid] || []).push(fx);
            }
            for (const [lid, fxs] of Object.entries(byId)) {
              leagueGroups.push({ id: parseInt(lid,10), season: s, date, fixtures: fxs });
            }
            gotForThisDate = true;
          }
        } catch (e) {
          if (e.message === "RATE_LIMIT") { console.log("RATE LIMIT — wait a minute and run again."); }
          else if (!firstError) firstError = e.message;
        }
        await sleep(SLEEP);
        if (gotForThisDate) break; // got this date on this season, move to next date
      }
    }
    console.log(`ALL mode: ${leagueGroups.length} league-days have fixtures in the window.`);
    if (MAX_LEAGUES && leagueGroups.length > MAX_LEAGUES) {
      console.log(`Capping to ${MAX_LEAGUES} league-days (set MAX_LEAGUES in config to change).`);
      leagueGroups.length = MAX_LEAGUES;
    }
  } else {
    // LIST mode: for each league, sweep every date in the window.
    // CAPS (important for very long league lists, esp. in off-season):
    //   MAX_LEAGUES    — stop after this many DISTINCT leagues yield fixtures.
    //   MAX_PROBES     — HARD stop after this many leagues EXAMINED, whether or
    //                    not they had games. This is the off-season safety net:
    //                    without it, a 400-id list probes every empty league.
    //   REQUEST_BUDGET — hard stop if total requests cross this ceiling.
    const REQUEST_BUDGET = cfg.REQUEST_BUDGET || 6000;
    const MAX_PROBES = cfg.MAX_PROBES || 120; // leagues examined per run, max
    const leaguesWithFixtures = new Set();
    let capped = false, probes = 0;
    for (const leagueId of cfg.LEAGUES) {
      if (capped) break;
      if (requests >= REQUEST_BUDGET) {
        console.log(`Request budget reached (${requests}/${REQUEST_BUDGET}) — stopping early to protect your daily quota.`);
        break;
      }
      if (MAX_LEAGUES && leaguesWithFixtures.size >= MAX_LEAGUES) {
        console.log(`League cap reached (${MAX_LEAGUES} with fixtures) — stopping.`);
        break;
      }
      if (probes >= MAX_PROBES) {
        console.log(`Probe limit reached (${MAX_PROBES} leagues examined) — stopping. Off-season: most had no games.`);
        break;
      }
      probes++;
      const seasonsToTry = [...new Set([season, String(parseInt(season,10)-1), String(parseInt(season,10)+1)])];

      // FAST EMPTY-SKIP: probe TODAY on the primary season first. If that one
      // call returns no games, treat the league as inactive and skip the other
      // 8 season/date combinations entirely. This is what kills the off-season
      // time sink (was up to 9 calls per empty league; now just 1).
      let resolvedSeason = null;
      try {
        const probe = await apiGet(`/fixtures?league=${leagueId}&season=${season}&date=${today}`, cfg.API_KEY);
        requests++;
        if ((probe.response || []).length) resolvedSeason = season;
      } catch (e) {
        if (e.message === "RATE_LIMIT") { console.log("RATE LIMIT — stopping early."); capped = true; break; }
        if (!firstError) firstError = e.message;
      }
      await sleep(SLEEP);

      // If today's primary season was empty, try today on the OTHER seasons once
      // each (handles season-rollover leagues) — but still just 1 call per season.
      if (!resolvedSeason) {
        for (const s of seasonsToTry) {
          if (s === season) continue;
          if (requests >= REQUEST_BUDGET) { capped = true; break; }
          try {
            const probe = await apiGet(`/fixtures?league=${leagueId}&season=${s}&date=${today}`, cfg.API_KEY);
            requests++;
            if ((probe.response || []).length) { resolvedSeason = s; await sleep(SLEEP); break; }
          } catch (e) { if (!firstError) firstError = e.message; }
          await sleep(SLEEP);
        }
      }

      if (capped) break;
      if (!resolvedSeason) { console.log(`League ${leagueId}: inactive (no games today) — skipped`); continue; }

      // League is ACTIVE — now sweep the full date window on the resolved season.
      for (const date of DATE_WINDOW) {
        if (requests >= REQUEST_BUDGET) { capped = true; break; }
        try {
          const fxRes = await apiGet(`/fixtures?league=${leagueId}&season=${resolvedSeason}&date=${date}`, cfg.API_KEY);
          requests++;
          const arr = fxRes.response || [];
          if (arr.length) {
            leagueGroups.push({ id: leagueId, season: resolvedSeason, date, fixtures: arr });
            leaguesWithFixtures.add(leagueId);
          }
        } catch (e) {
          if (e.message === "RATE_LIMIT") { console.log("RATE LIMIT — stopping early."); capped = true; break; }
          if (!firstError) firstError = e.message;
        }
        await sleep(SLEEP);
      }
    }
    console.log(`LIST mode: examined ${probes} league(s), ${leaguesWithFixtures.size} had fixtures (caps: ${MAX_LEAGUES||"∞"} active / ${MAX_PROBES} probed).`);
  }

  // -----------------------------------------------------------------
  // STEP 2: standings are per league+season and DON'T change by date,
  // so fetch each (league,season) ONCE and cache it. This is the key
  // saving that keeps a multi-day window affordable.
  // -----------------------------------------------------------------
  // Parse one /standings API block into our table structure. Returns null
  // if the block has no usable rows, so the caller can try another season.
  function parseStandingsBlock(block) {
    if (!block) return null;
    const groups = block.league.standings || [];
    let table = {}, multiGroup = groups.length > 1, count = 0;
    const allRows = [];
    for (const g of groups) {
      for (const row of g) {
        const grpName = row.group || (block.league.name + (multiGroup ? " (grp)" : ""));
        table[row.team.id] = { ...row, _group: grpName };
        allRows.push(table[row.team.id]);
        count++;
      }
    }
    if (!count) return null; // empty table — let caller fall back to another season
    const tableSize = groups.length === 1 ? groups[0].length : count;

    // ---- LEAGUE BASELINE AVERAGES (no extra API calls) ----
    // Sum each team's season totals across the table to get the league's own
    // "normal": goals per game, draw rate, home-win rate. The engine uses these
    // to judge a match RELATIVE to its league instead of one global assumption.
    // Marked unreliable (and ignored) if too few games have been played, so we
    // never calibrate to a noisy small sample (early season / sparse division).
    let sumPlayed = 0, sumGoals = 0, sumDraws = 0, sumHomeWins = 0, sumHomePlayed = 0;
    for (const r of allRows) {
      const a = r.all || {};
      const p = a.played || 0;
      sumPlayed += p;
      sumGoals  += (a.goals && (a.goals.for || 0)) || 0;        // goals scored (for)
      sumGoals  += (a.goals && (a.goals.against || 0)) || 0;    // + conceded = all goals, counted twice
      sumDraws  += (a.draw || 0);
      const h = r.home || {};
      sumHomePlayed += (h.played || 0);
      sumHomeWins   += (h.win || 0);
    }
    // each game appears twice across the two teams' rows, so divide team-sums by 2
    const gamesApprox = sumPlayed / 2;
    const avgGamesPerTeam = tableSize ? sumPlayed / tableSize : 0;
    const leagueAvg = {
      goalsPerGame: gamesApprox > 0 ? Math.round((sumGoals / 2 / gamesApprox) * 100) / 100 : null,
      drawRate:     sumPlayed  > 0 ? Math.round((sumDraws / sumPlayed) * 100) / 100 : null, // draws counted per-team = per-game share
      homeWinRate:  sumHomePlayed > 0 ? Math.round((sumHomeWins / sumHomePlayed) * 100) / 100 : null,
      gamesPlayed:  Math.round(gamesApprox),
      // reliable only if teams have played a reasonable number of games
      reliable:     avgGamesPerTeam >= 5,
    };
    const byGroup = {};
    for (const r of allRows) (byGroup[r._group] = byGroup[r._group] || []).push(r);
    for (const grp of Object.values(byGroup)) {
      const homeSorted = [...grp].sort((a,b)=>{
        const ap=(a.home&&a.home.points!=null)?a.home.points:homePtsFromRow(a.home), bp=(b.home&&b.home.points!=null)?b.home.points:homePtsFromRow(b.home);
        if (bp!==ap) return bp-ap;
        return gdOf(b.home)-gdOf(a.home);
      });
      homeSorted.forEach((r,i)=>{ r._homeRank = i+1; r._homePts = (r.home&&r.home.points!=null)?r.home.points:homePtsFromRow(r.home); r._homeGames = (r.home&&r.home.played!=null)?r.home.played:null; });
      const awaySorted = [...grp].sort((a,b)=>{
        const ap=(a.away&&a.away.points!=null)?a.away.points:homePtsFromRow(a.away), bp=(b.away&&b.away.points!=null)?b.away.points:homePtsFromRow(b.away);
        if (bp!==ap) return bp-ap;
        return gdOf(b.away)-gdOf(a.away);
      });
      awaySorted.forEach((r,i)=>{ r._awayRank = i+1; r._awayPts = (r.away&&r.away.points!=null)?r.away.points:homePtsFromRow(r.away); r._awayGames = (r.away&&r.away.played!=null)?r.away.played:null; });
      grp.forEach(r=>{ r._groupSize = grp.length; });
    }
    return { table, tableSize, leagueName: block.league.name, multiGroup, leagueAvg };
  }

  // Standings don't change by date, so fetch each league ONCE and cache it.
  // We try the resolved season first, then ±1, so domestic leagues (e.g.
  // 2025/26 -> 2025) and one-off tournaments (e.g. World Cup -> 2026) both
  // find a real table from a single SEASON= setting, year-round.
  const standingsCache = {}; // key `${leagueId}` -> { table, tableSize, leagueName, multiGroup, season }
  async function getStandings(leagueId, seasonForStandings) {
    const cacheKey = `${leagueId}`;
    if (standingsCache[cacheKey]) return standingsCache[cacheKey];
    // de-duped season candidates: the one fixtures resolved to, then prev, then next
    const base = parseInt(seasonForStandings, 10);
    const seasonCandidates = [...new Set([ String(base), String(base-1), String(base+1) ])];
    let parsed = null, usedSeason = seasonForStandings;
    for (const s of seasonCandidates) {
      try {
        const stRes = await apiGet(`/standings?league=${leagueId}&season=${s}`, cfg.API_KEY); requests++;
        const block = stRes.response && stRes.response[0];
        const got = parseStandingsBlock(block);
        await sleep(SLEEP);
        if (got) { parsed = got; usedSeason = s; break; }
      } catch (e) {
        console.log(`League ${leagueId}: standings season ${s} failed (${e.message})`);
        await sleep(SLEEP);
      }
    }
    const result = parsed
      ? { ...parsed, season: usedSeason }
      : { table: {}, tableSize: 20, leagueName: `League ${leagueId}`, multiGroup: false, season: seasonForStandings };
    if (!parsed) console.log(`League ${leagueId}: no standings in seasons ${seasonCandidates.join("/")} — neutral stats`);
    standingsCache[cacheKey] = result;
    return result;
  }

  // odds are per league+date; cache by `${leagueId}|${season}|${date}`
  const oddsCache = {};
  const teamStatsCache = {}; // key `${teamId}|${leagueId}|${season}` -> stats object
  const wantStats = cfg.STATS !== false; // set STATS=false secret to disable

  // Fetch REAL season stats for one team in one league (cached per run).
  // Returns { winRate, drawRate, lossRate, unbeatenRate, cleanSheetRate,
  //           failedToScoreRate, ... } home/away split where available.
  async function getTeamStats(teamId, leagueId, season){
    if (!wantStats || !teamId || !leagueId) return null;
    const ck = `${teamId}|${leagueId}|${season}`;
    if (teamStatsCache[ck] !== undefined) return teamStatsCache[ck];
    let stats = null;
    try {
      const res = await apiGet(`/teams/statistics?team=${teamId}&league=${leagueId}&season=${season}`, cfg.API_KEY); requests++;
      const r = res.response;
      if (r && r.fixtures) {
        const f = r.fixtures, cs = r.clean_sheet || {}, fts = r.failed_to_score || {};
        const played = (f.played && f.played.total) || 0;
        const wins = (f.wins && f.wins.total) || 0;
        const draws = (f.draws && f.draws.total) || 0;
        const loses = (f.loses && f.loses.total) || 0;
        const csTotal = cs.total || 0, ftsTotal = fts.total || 0;
        // home/away splits (used by the home-advantage engine)
        const hPlayed=(f.played&&f.played.home)||0, aPlayed=(f.played&&f.played.away)||0;
        const hWins=(f.wins&&f.wins.home)||0, aWins=(f.wins&&f.wins.away)||0;
        const hDraws=(f.draws&&f.draws.home)||0, aDraws=(f.draws&&f.draws.away)||0;
        stats = {
          played,
          winRate: played? wins/played : null,
          drawRate: played? draws/played : null,
          lossRate: played? loses/played : null,
          unbeatenRate: played? (wins+draws)/played : null,
          cleanSheetRate: played? csTotal/played : null,
          failedToScoreRate: played? ftsTotal/played : null,
          homeWinRate: hPlayed? hWins/hPlayed : null,
          awayWinRate: aPlayed? aWins/aPlayed : null,
          homeUnbeatenRate: hPlayed? (hWins+hDraws)/hPlayed : null,
          awayUnbeatenRate: aPlayed? (aWins+aDraws)/aPlayed : null,
          cleanSheetHome: (cs.home!=null&&hPlayed)? cs.home/hPlayed : null,
          cleanSheetAway: (cs.away!=null&&aPlayed)? cs.away/aPlayed : null,
          ftsHome: (fts.home!=null&&hPlayed)? fts.home/hPlayed : null,
          ftsAway: (fts.away!=null&&aPlayed)? fts.away/aPlayed : null,
        };
      }
      await sleep(SLEEP);
    } catch (e) { /* stats optional — fall back to estimates */ }
    teamStatsCache[ck] = stats;
    return stats;
  }
  async function getOdds(leagueId, seasonForStandings, date) {
    if (!wantOdds) return {};
    const cacheKey = `${leagueId}|${seasonForStandings}|${date}`;
    if (oddsCache[cacheKey]) return oddsCache[cacheKey];
    const oddsByFixture = {};
    try {
      const odRes = await apiGet(`/odds?league=${leagueId}&season=${seasonForStandings}&date=${date}`, cfg.API_KEY); requests++;
      for (const entry of (odRes.response || [])) {
        const fid = entry.fixture && entry.fixture.id;
        if (!fid) continue;
        let vals = null;
        for (const bk of (entry.bookmakers || [])) {
          const bet = (bk.bets || []).find(b => /match winner|1x2|full time result/i.test(b.name || ""));
          if (bet && bet.values) {
            const get = lbl => { const v = bet.values.find(x => new RegExp(lbl,"i").test(x.value)); return v ? parseFloat(v.odd) : null; };
            const h = get("^home|^1$"), d = get("^draw|^x$"), a = get("^away|^2$");
            if (h && a) { vals = { home: h, draw: d, away: a }; break; }
          }
        }
        if (vals) oddsByFixture[fid] = vals;
      }
      await sleep(SLEEP);
    } catch (e) { /* odds optional — ignore failures */ }
    oddsCache[cacheKey] = oddsByFixture;
    return oddsByFixture;
  }

  // -----------------------------------------------------------------
  // STEP 3: process every league-day group: standings (cached) + odds
  // (cached) + per-match H2H, then build the match record. matchDate is
  // grp.date — the REAL date of the fixture.
  // -----------------------------------------------------------------
  for (const grp of leagueGroups) {
    const leagueId = grp.id;
    const seasonForStandings = grp.season;
    const date = grp.date;
    const fixtures = grp.fixtures;

    const standings = await getStandings(leagueId, seasonForStandings);
    const { table, tableSize, multiGroup } = standings;
    const leagueAvg = standings.leagueAvg || null;
    let leagueName = standings.leagueName;
    let leagueCountry = null, leagueFlag = null;
    if (fixtures[0].league) {
      if (fixtures[0].league.name) leagueName = fixtures[0].league.name;
      // country + flag image URL come free in the fixture's league block
      leagueCountry = fixtures[0].league.country || null;
      leagueFlag = fixtures[0].league.flag || null;
    }

    const oddsByFixture = await getOdds(leagueId, seasonForStandings, date);

    for (const fx of fixtures) {
      const st = fx.fixture.status.short;
      const H = table[fx.teams.home.id] || {}, A = table[fx.teams.away.id] || {};
      const hHome = H.home || {}, aAway = A.away || {};
      const played = FINISHED.has(st);
      const homeGroup = H._group || null, awayGroup = A._group || null;
      const sameGroup = !!(homeGroup && awayGroup && homeGroup === awayGroup);
      const roundName = (fx.league && fx.league.round) ? String(fx.league.round) : "";
      const isKnockout = /final|semi|quarter|round of|knockout|1\/|play-?off/i.test(roundName);

      // ---- HEAD-TO-HEAD: full H2H on every day in the window (your choice) ----
      let h2h = null;
      if (wantH2H) {
        try {
          const hid = fx.teams.home.id, aid = fx.teams.away.id;
          const hr = await apiGet(`/fixtures/headtohead?h2h=${hid}-${aid}&last=6`, cfg.API_KEY); requests++;
          const games = (hr.response || []).filter(g => FINISHED.has(g.fixture.status.short));
          if (games.length) {
            let homeWins=0, awayWins=0, draws=0, over25=0, bttsCount=0;
            const recent = [];
            for (const g of games) {
              const gh=g.goals.home, ga=g.goals.away;
              if (gh==null||ga==null) continue;
              let res;
              if (gh===ga) { draws++; res="D"; }
              else {
                const winId = gh>ga ? g.teams.home.id : g.teams.away.id;
                if (winId===hid) { homeWins++; res="H"; } else if (winId===aid) { awayWins++; res="A"; } else res="?";
              }
              if (gh+ga>=3) over25++;
              if (gh>0 && ga>0) bttsCount++;
              recent.push({ date:(g.fixture.date||"").slice(0,10),
                ht:g.teams.home.name, at:g.teams.away.name, hg:gh, ag:ga, res });
            }
            h2h = { played:games.length, homeWins, awayWins, draws, over25, bttsCount, recent:recent.slice(0,5) };
          }
          await sleep(SLEEP);
        } catch (e) { /* h2h optional */ }
      }

      // REAL team stats (cached per team per run) — only fetch for games not
      // already finished, to contain cost (no point fetching for settled games).
      let homeStats = null, awayStats = null;
      if (wantStats && st !== "FT" && st !== "AET" && st !== "PEN") {
        const hid = fx.teams.home.id, aid = fx.teams.away.id;
        homeStats = await getTeamStats(hid, leagueId, seasonForStandings);
        awayStats = await getTeamStats(aid, leagueId, seasonForStandings);
      }

      out.push({
        home: fx.teams.home.name, away: fx.teams.away.name, league: leagueName,
        country: leagueCountry, flag: leagueFlag,
        status: st, kickoff: fx.fixture.date || null, matchDate: date,
        homeGoals: (fx.goals && fx.goals.home != null) ? fx.goals.home : null,
        awayGoals: (fx.goals && fx.goals.away != null) ? fx.goals.away : null,
        homePos: H.rank ?? null, awayPos: A.rank ?? null, tableSize,
        homePts: H.points ?? 0, awayPts: A.points ?? 0,
        homeGD: H.goalsDiff ?? 0, awayGD: A.goalsDiff ?? 0,
        homeForm: cleanForm(H.form), awayForm: cleanForm(A.form),
        homeScoredAtHome: round1(hHome.played ? hHome.goals.for/hHome.played : 1.3),
        homeConcededAtHome: round1(hHome.played ? hHome.goals.against/hHome.played : 1.1),
        awayScoredAway: round1(aAway.played ? aAway.goals.for/aAway.played : 1.0),
        awayConcededAway: round1(aAway.played ? aAway.goals.against/aAway.played : 1.4),
        homeVenueRank: H._homeRank ?? null, awayVenueRank: A._awayRank ?? null,
        homeVenuePts: H._homePts ?? null, awayVenuePts: A._awayPts ?? null,
        homeVenueGames: H._homeGames ?? null, awayVenueGames: A._awayGames ?? null,
        venueTableSize: H._groupSize ?? A._groupSize ?? tableSize,
        leagueAvg,  // per-league baseline averages for engine calibration
        // REAL stats (null when unavailable -> engines fall back to estimates)
        homeWinRate: homeStats ? round2(homeStats.homeWinRate ?? homeStats.winRate) : null,
        awayWinRate: awayStats ? round2(awayStats.awayWinRate ?? awayStats.winRate) : null,
        homeUnbeatenRate: homeStats ? round2(homeStats.homeUnbeatenRate ?? homeStats.unbeatenRate) : null,
        awayUnbeatenRate: awayStats ? round2(awayStats.awayUnbeatenRate ?? awayStats.unbeatenRate) : null,
        homeCleanSheetRate: homeStats ? round2(homeStats.cleanSheetHome ?? homeStats.cleanSheetRate) : null,
        awayCleanSheetRate: awayStats ? round2(awayStats.cleanSheetAway ?? awayStats.cleanSheetRate) : null,
        homeFailedToScoreRate: homeStats ? round2(homeStats.ftsHome ?? homeStats.failedToScoreRate) : null,
        awayFailedToScoreRate: awayStats ? round2(awayStats.ftsAway ?? awayStats.failedToScoreRate) : null,
        statsReal: !!(homeStats || awayStats),
        sameGroup, isKnockout,
        isTournament: multiGroup || isKnockout,
        round: roundName || null,
        odds: oddsByFixture[fx.fixture.id] || null,
        h2h,
      });
      console.log(`  + [${date}] ${fx.teams.home.name} vs ${fx.teams.away.name}${played?` (${fx.goals.home}-${fx.goals.away} FT)`:""}  [${leagueName}]${isKnockout?" (KO)":""}`);
    }
    await sleep(SLEEP);
  }

  if (!out.length) {
    if (firstError) {
      console.log("\nNo matches saved. First issue: " + firstError);
      if (firstError.includes("season")) console.log("If it mentions the season, your plan may not cover it. Pro unlocks current seasons.");
    } else {
      console.log("\nNo fixtures in the window in your leagues (off-season is normal in summer).");
      console.log("The World Cup is league ID 1 — make sure it's in config.txt.");
    }
    console.log("Leaving your existing data.js untouched (not overwriting with empty).\n");
    return;
  }

  // -----------------------------------------------------------------
  // MERGE: keep any saved days that are OUTSIDE this run's window
  // untouched, and replace every day that IS in the window with the
  // freshly fetched data. (Previously this only replaced 'today'.)
  // -----------------------------------------------------------------
  let existing = [];
  try {
    const prev = fs.readFileSync(path.join(HERE, "data.js"), "utf8");
    const m = prev.match(/window\.MATCHES\s*=\s*(\[[\s\S]*\]);?\s*$/);
    if (m) existing = JSON.parse(m[1]);
  } catch (e) {}
  const windowSet = new Set(DATE_WINDOW);
  const kept = existing.filter(x => x.matchDate && !windowSet.has(x.matchDate));
  const merged = kept.concat(out);
  merged.sort((a,b)=>{ if(a.matchDate!==b.matchDate) return (b.matchDate||"").localeCompare(a.matchDate||""); return (a.kickoff||"").localeCompare(b.kickoff||""); });

  fs.writeFileSync(path.join(HERE, "data.js"),
    "/* AUTO-GENERATED by fetch-data.js on " + new Date().toLocaleString() + " — do not edit by hand. */\n\n" +
    "window.DATA_UPDATED = \"" + new Date().toISOString() + "\";\n" +
    "window.MATCHES = " + JSON.stringify(merged, null, 2) + ";\n", "utf8");

  const finishedCount = out.filter(x=>x.homeGoals!=null).length;
  const daysCovered = [...new Set(out.map(x=>x.matchDate))].sort();
  console.log(`\nDone. Window: ${out.length} match(es) across ${daysCovered.length} day(s) [${daysCovered.join(", ")}] (${finishedCount} finished). ${requests} requests used.`);
  console.log(`Board now holds ${merged.length} match(es) across all saved days.`);
  console.log("Next: commit data.js (the workflow deploys it), or for local runs upload your folder.\n");
})();
