/* Starter fixture feed generated from the uploaded repository. The workflow replaces this file. */
window.FIXTURE_DATA_UPDATED = "2026-07-14T07:51:26.469262Z";
window.FIXTURE_WINDOW = {
  "generatedAt": "2026-07-14T07:51:26.469262Z",
  "windowStart": "2026-07-14",
  "windowEnd": "2026-07-20",
  "totalFixtures": 81,
  "daysRequested": 7,
  "dateCounts": {
    "2026-07-14": 47,
    "2026-07-15": 34
  },
  "starterFromExistingData": true
};
window.FIXTURES = [
  {
    "id": 1498633,
    "home": "Atlanta",
    "away": "Colegiales",
    "league": "Primera Nacional",
    "leagueId": 129,
    "season": "2026",
    "round": "Regular Season - 20",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 1948,
    "awayTeamId": 8377,
    "homeLogo": "https://media.api-sports.io/football/teams/1948.png",
    "awayLogo": "https://media.api-sports.io/football/teams/8377.png",
    "status": "FT",
    "statusLong": "Match Finished",
    "elapsed": null,
    "kickoff": "2026-07-14T00:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": 1,
    "awayGoals": 0,
    "htHome": 0,
    "htAway": 0,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1544686,
    "home": "Cavalry FC",
    "away": "Vancouver Whitecaps",
    "league": "Canadian Championship",
    "leagueId": 259,
    "season": "2026",
    "round": "Quarter-finals",
    "country": "Canada",
    "flag": "https://media.api-sports.io/flags/ca.svg",
    "homeTeamId": 2619,
    "awayTeamId": 1603,
    "homeLogo": "https://media.api-sports.io/football/teams/2619.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1603.png",
    "status": "FT",
    "statusLong": "Match Finished",
    "elapsed": null,
    "kickoff": "2026-07-14T01:30:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": 1,
    "awayGoals": 1,
    "htHome": 0,
    "htAway": 0,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1523197,
    "home": "Hangzhou Greentown",
    "away": "Qingdao Jonoon",
    "league": "Super League",
    "leagueId": 169,
    "season": "2026",
    "round": "Regular Season - 18",
    "country": "China",
    "flag": "https://media.api-sports.io/flags/cn.svg",
    "homeTeamId": 848,
    "awayTeamId": 1431,
    "homeLogo": "https://media.api-sports.io/football/teams/848.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1431.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T11:35:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554381,
    "home": "KuPS",
    "away": "Vardar Skopje",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 1165,
    "awayTeamId": 574,
    "homeLogo": "https://media.api-sports.io/football/teams/1165.png",
    "awayLogo": "https://media.api-sports.io/football/teams/574.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T15:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1541526,
    "home": "Ilves II",
    "away": "GrIFK",
    "league": "Kakkonen - Lohko B",
    "leagueId": 248,
    "season": "2026",
    "round": "Group B",
    "country": "Finland",
    "flag": "https://media.api-sports.io/flags/fi.svg",
    "homeTeamId": 9185,
    "awayTeamId": 2079,
    "homeLogo": "https://media.api-sports.io/football/teams/9185.png",
    "awayLogo": "https://media.api-sports.io/football/teams/2079.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T16:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554380,
    "home": "Inter Club d'Escaldes",
    "away": "Lincoln Red Imps FC",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 3342,
    "awayTeamId": 667,
    "homeLogo": "https://media.api-sports.io/football/teams/3342.png",
    "awayLogo": "https://media.api-sports.io/football/teams/667.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T16:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554379,
    "home": "Saburtalo",
    "away": "Flora Tallinn",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 3502,
    "awayTeamId": 687,
    "homeLogo": "https://media.api-sports.io/football/teams/3502.png",
    "awayLogo": "https://media.api-sports.io/football/teams/687.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T16:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1514244,
    "home": "HK Kopavogur",
    "away": "IR Reykjavik",
    "league": "1. Deild",
    "leagueId": 165,
    "season": "2026",
    "round": "Regular Season - 16",
    "country": "Iceland",
    "flag": "https://media.api-sports.io/flags/is.svg",
    "homeTeamId": 2113,
    "awayTeamId": 2122,
    "homeLogo": "https://media.api-sports.io/football/teams/2113.png",
    "awayLogo": "https://media.api-sports.io/football/teams/2122.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T17:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554378,
    "home": "Gyori ETO FC",
    "away": "Vikingur Reykjavik",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 2402,
    "awayTeamId": 278,
    "homeLogo": "https://media.api-sports.io/football/teams/2402.png",
    "awayLogo": "https://media.api-sports.io/football/teams/278.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T17:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554384,
    "home": "Riga",
    "away": "Ararat-Armenia",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 10124,
    "awayTeamId": 3683,
    "homeLogo": "https://media.api-sports.io/football/teams/10124.png",
    "awayLogo": "https://media.api-sports.io/football/teams/3683.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T17:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554387,
    "home": "The New Saints",
    "away": "Sabah FA",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 354,
    "awayTeamId": 13976,
    "homeLogo": "https://media.api-sports.io/football/teams/354.png",
    "awayLogo": "https://media.api-sports.io/football/teams/13976.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T17:30:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554383,
    "home": "Levski Sofia",
    "away": "Borac Banja Luka",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 646,
    "awayTeamId": 3364,
    "homeLogo": "https://media.api-sports.io/football/teams/646.png",
    "awayLogo": "https://media.api-sports.io/football/teams/3364.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T17:30:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1514200,
    "home": "Grotta",
    "away": "Grindavik",
    "league": "1. Deild",
    "leagueId": 165,
    "season": "2026",
    "round": "Regular Season - 8",
    "country": "Iceland",
    "flag": "https://media.api-sports.io/flags/is.svg",
    "homeTeamId": 2121,
    "awayTeamId": 277,
    "homeLogo": "https://media.api-sports.io/football/teams/2121.png",
    "awayLogo": "https://media.api-sports.io/football/teams/277.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499526,
    "home": "Flandria",
    "away": "Argentino de Merlo",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 471,
    "awayTeamId": 2430,
    "homeLogo": "https://media.api-sports.io/football/teams/471.png",
    "awayLogo": "https://media.api-sports.io/football/teams/2430.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499521,
    "home": "Defensores Unidos",
    "away": "Excursionistas",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 1945,
    "awayTeamId": 8385,
    "homeLogo": "https://media.api-sports.io/football/teams/1945.png",
    "awayLogo": "https://media.api-sports.io/football/teams/8385.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499525,
    "home": "Dock Sud",
    "away": "UAI Urquiza",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 2429,
    "awayTeamId": 1956,
    "homeLogo": "https://media.api-sports.io/football/teams/2429.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1956.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499524,
    "home": "Deportivo Camioneros",
    "away": "Liniers",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 3943,
    "awayTeamId": 8395,
    "homeLogo": "https://media.api-sports.io/football/teams/3943.png",
    "awayLogo": "https://media.api-sports.io/football/teams/8395.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499518,
    "home": "Argentino Quilmes",
    "away": "Arsenal Sarandi",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 8376,
    "awayTeamId": 459,
    "homeLogo": "https://media.api-sports.io/football/teams/8376.png",
    "awayLogo": "https://media.api-sports.io/football/teams/459.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499528,
    "home": "Sportivo Italiano",
    "away": "Villa San Carlos",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 8388,
    "awayTeamId": 8380,
    "homeLogo": "https://media.api-sports.io/football/teams/8388.png",
    "awayLogo": "https://media.api-sports.io/football/teams/8380.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554376,
    "home": "Drita",
    "away": "Kauno \u017dalgiris",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 14281,
    "awayTeamId": 3872,
    "homeLogo": "https://media.api-sports.io/football/teams/14281.png",
    "awayLogo": "https://media.api-sports.io/football/teams/3872.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499523,
    "home": "Deportivo Armenio",
    "away": "Talleres Remedios",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 2427,
    "awayTeamId": 1927,
    "homeLogo": "https://media.api-sports.io/football/teams/2427.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1927.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:30:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548132,
    "home": "Kilmarnock",
    "away": "Raith Rovers",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 250,
    "awayTeamId": 1385,
    "homeLogo": "https://media.api-sports.io/football/teams/250.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1385.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548125,
    "home": "Dunfermline",
    "away": "Dumbarton",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 1388,
    "awayTeamId": 1382,
    "homeLogo": "https://media.api-sports.io/football/teams/1388.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1382.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548129,
    "home": "Falkirk",
    "away": "Ayr Utd",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 1389,
    "awayTeamId": 1387,
    "homeLogo": "https://media.api-sports.io/football/teams/1389.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1387.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548121,
    "home": "Brechin",
    "away": "Livingston",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 1390,
    "awayTeamId": 255,
    "homeLogo": "https://media.api-sports.io/football/teams/1390.png",
    "awayLogo": "https://media.api-sports.io/football/teams/255.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548130,
    "home": "Forfar Athletic",
    "away": "Partick",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 4250,
    "awayTeamId": 901,
    "homeLogo": "https://media.api-sports.io/football/teams/4250.png",
    "awayLogo": "https://media.api-sports.io/football/teams/901.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548134,
    "home": "Montrose",
    "away": "Dundee Utd",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 4251,
    "awayTeamId": 1386,
    "homeLogo": "https://media.api-sports.io/football/teams/4251.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1386.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548133,
    "home": "Linlithgow Rose",
    "away": "ST Johnstone",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 6744,
    "awayTeamId": 258,
    "homeLogo": "https://media.api-sports.io/football/teams/6744.png",
    "awayLogo": "https://media.api-sports.io/football/teams/258.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548120,
    "home": "Annan Athletic",
    "away": "Dundee",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 6757,
    "awayTeamId": 253,
    "homeLogo": "https://media.api-sports.io/football/teams/6757.png",
    "awayLogo": "https://media.api-sports.io/football/teams/253.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548122,
    "home": "Brora Rangers",
    "away": "Aberdeen",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 6760,
    "awayTeamId": 252,
    "homeLogo": "https://media.api-sports.io/football/teams/6760.png",
    "awayLogo": "https://media.api-sports.io/football/teams/252.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548123,
    "home": "Clyde",
    "away": "Airdrie United",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 6762,
    "awayTeamId": 4668,
    "homeLogo": "https://media.api-sports.io/football/teams/6762.png",
    "awayLogo": "https://media.api-sports.io/football/teams/4668.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548124,
    "home": "Cove Rangers",
    "away": "East Kilbride",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 6763,
    "awayTeamId": 6765,
    "homeLogo": "https://media.api-sports.io/football/teams/6763.png",
    "awayLogo": "https://media.api-sports.io/football/teams/6765.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548126,
    "home": "East Fife",
    "away": "Morton",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 6764,
    "awayTeamId": 1383,
    "homeLogo": "https://media.api-sports.io/football/teams/6764.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1383.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548127,
    "home": "Edinburgh City",
    "away": "Alloa Athletic",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 6766,
    "awayTeamId": 1391,
    "homeLogo": "https://media.api-sports.io/football/teams/6766.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1391.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548128,
    "home": "Elgin City",
    "away": "Peterhead",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 6767,
    "awayTeamId": 6777,
    "homeLogo": "https://media.api-sports.io/football/teams/6767.png",
    "awayLogo": "https://media.api-sports.io/football/teams/6777.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548131,
    "home": "Kelty Hearts",
    "away": "Queen's Park",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 6773,
    "awayTeamId": 6778,
    "homeLogo": "https://media.api-sports.io/football/teams/6773.png",
    "awayLogo": "https://media.api-sports.io/football/teams/6778.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1548135,
    "home": "Spartans",
    "away": "Stirling Albion",
    "league": "League Cup",
    "leagueId": 185,
    "season": "2026",
    "round": "Group Stage",
    "country": "Scotland",
    "flag": "https://media.api-sports.io/flags/gb-sct.svg",
    "homeTeamId": 6781,
    "awayTeamId": 4669,
    "homeLogo": "https://media.api-sports.io/football/teams/6781.png",
    "awayLogo": "https://media.api-sports.io/football/teams/4669.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T18:45:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554385,
    "home": "Shamrock Rovers",
    "away": "Floriana",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 652,
    "awayTeamId": 4625,
    "homeLogo": "https://media.api-sports.io/football/teams/652.png",
    "awayLogo": "https://media.api-sports.io/football/teams/4625.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T19:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554382,
    "home": "Larne",
    "away": "Tre Fiori",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 5354,
    "awayTeamId": 2260,
    "homeLogo": "https://media.api-sports.io/football/teams/5354.png",
    "awayLogo": "https://media.api-sports.io/football/teams/2260.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T19:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1585131,
    "home": "France",
    "away": "Spain",
    "league": "World Cup",
    "leagueId": 1,
    "season": "2026",
    "round": "Semi-finals",
    "country": "World",
    "flag": null,
    "homeTeamId": 2,
    "awayTeamId": 9,
    "homeLogo": "https://media.api-sports.io/football/teams/2.png",
    "awayLogo": "https://media.api-sports.io/football/teams/9.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T19:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1519404,
    "home": "Macara",
    "away": "Mushuc Runa SC",
    "league": "Liga Pro",
    "leagueId": 242,
    "season": "2026",
    "round": "Regular Season - 19",
    "country": "Ecuador",
    "flag": "https://media.api-sports.io/flags/ec.svg",
    "homeTeamId": 1155,
    "awayTeamId": 1162,
    "homeLogo": "https://media.api-sports.io/football/teams/1155.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1162.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T21:30:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499519,
    "home": "Brown DE Adrogue",
    "away": "Deportivo Laferrere",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 468,
    "awayTeamId": 1924,
    "homeLogo": "https://media.api-sports.io/football/teams/468.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1924.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T22:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499520,
    "home": "Comunicaciones",
    "away": "Villa Dalmine",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 8008,
    "awayTeamId": 481,
    "homeLogo": "https://media.api-sports.io/football/teams/8008.png",
    "awayLogo": "https://media.api-sports.io/football/teams/481.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T22:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499522,
    "home": "Deportivo Merlo",
    "away": "Real Pilar",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 8383,
    "awayTeamId": 2422,
    "homeLogo": "https://media.api-sports.io/football/teams/8383.png",
    "awayLogo": "https://media.api-sports.io/football/teams/2422.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T22:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1499527,
    "home": "Ituzaing\u00f3",
    "away": "San Mart\u00edn Burzaco",
    "league": "Primera B Metropolitana",
    "leagueId": 131,
    "season": "2026",
    "round": "Regular Season - 25",
    "country": "Argentina",
    "flag": "https://media.api-sports.io/flags/ar.svg",
    "homeTeamId": 8386,
    "awayTeamId": 8387,
    "homeLogo": "https://media.api-sports.io/football/teams/8386.png",
    "awayLogo": "https://media.api-sports.io/football/teams/8387.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T22:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1538383,
    "home": "Real Oruro",
    "away": "Always Ready",
    "league": "Primera Divisi\u00f3n",
    "leagueId": 344,
    "season": "2026",
    "round": "Apertura - 8",
    "country": "Bolivia",
    "flag": "https://media.api-sports.io/flags/bo.svg",
    "homeTeamId": 20252,
    "awayTeamId": 3700,
    "homeLogo": "https://media.api-sports.io/football/teams/20252.png",
    "awayLogo": "https://media.api-sports.io/football/teams/3700.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T22:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1586078,
    "home": "Asheville City",
    "away": "Virginia Beach City",
    "league": "USL League Two",
    "leagueId": 256,
    "season": "2026",
    "round": "Final Play-in",
    "country": "USA",
    "flag": "https://media.api-sports.io/flags/us.svg",
    "homeTeamId": 10094,
    "awayTeamId": 13192,
    "homeLogo": "https://media.api-sports.io/football/teams/10094.png",
    "awayLogo": "https://media.api-sports.io/football/teams/13192.png",
    "status": "NS",
    "statusLong": "Not Started",
    "elapsed": null,
    "kickoff": "2026-07-14T23:00:00+00:00",
    "matchDate": "2026-07-14",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1519405,
    "home": "Manta FC",
    "away": "Delfin SC",
    "league": "Liga Pro",
    "leagueId": 242,
    "season": "2026",
    "round": "Regular Season - 19",
    "country": "Ecuador",
    "flag": "https://media.api-sports.io/flags/ec.svg",
    "homeTeamId": 1980,
    "awayTeamId": 1149,
    "homeLogo": "https://media.api-sports.io/football/teams/1980.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1149.png",
    "status": "NS",
    "kickoff": "2026-07-15T00:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1538384,
    "home": "Blooming",
    "away": "Gualberto Villarroel SJ",
    "league": "Primera Divisi\u00f3n",
    "leagueId": 344,
    "season": "2026",
    "round": "Apertura - 8",
    "country": "Bolivia",
    "flag": "https://media.api-sports.io/flags/bo.svg",
    "homeTeamId": 3701,
    "awayTeamId": 22266,
    "homeLogo": "https://media.api-sports.io/football/teams/3701.png",
    "awayLogo": "https://media.api-sports.io/football/teams/22266.png",
    "status": "NS",
    "kickoff": "2026-07-15T00:30:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1586079,
    "home": "New England FC",
    "away": "Ironbound",
    "league": "USL League Two",
    "leagueId": 256,
    "season": "2026",
    "round": "Final Play-in",
    "country": "USA",
    "flag": "https://media.api-sports.io/flags/us.svg",
    "homeTeamId": 26064,
    "awayTeamId": 21283,
    "homeLogo": "https://media.api-sports.io/football/teams/26064.png",
    "awayLogo": "https://media.api-sports.io/football/teams/21283.png",
    "status": "NS",
    "kickoff": "2026-07-15T00:30:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581358,
    "home": "Daegu FC",
    "away": "Siheung Citizen",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 2747,
    "awayTeamId": 7105,
    "homeLogo": "https://media.api-sports.io/football/teams/2747.png",
    "awayLogo": "https://media.api-sports.io/football/teams/7105.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581362,
    "home": "Suwon City FC",
    "away": "Pyeongchang United",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 2756,
    "awayTeamId": 18656,
    "homeLogo": "https://media.api-sports.io/football/teams/2756.png",
    "awayLogo": "https://media.api-sports.io/football/teams/18656.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581361,
    "home": "Seongnam FC",
    "away": "Pocheon",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 2757,
    "awayTeamId": 7099,
    "homeLogo": "https://media.api-sports.io/football/teams/2757.png",
    "awayLogo": "https://media.api-sports.io/football/teams/7099.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581355,
    "home": "Ansan Greeners",
    "away": "Jinju Citizen",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 2758,
    "awayTeamId": 16452,
    "homeLogo": "https://media.api-sports.io/football/teams/2758.png",
    "awayLogo": "https://media.api-sports.io/football/teams/16452.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1557966,
    "home": "Jeonnam Dragons",
    "away": "Asan Mugunghwa",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 2760,
    "awayTeamId": 2753,
    "homeLogo": "https://media.api-sports.io/football/teams/2760.png",
    "awayLogo": "https://media.api-sports.io/football/teams/2753.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581837,
    "home": "Busan Transportation",
    "away": "Suwon Bluewings",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 7056,
    "awayTeamId": 2765,
    "homeLogo": "https://media.api-sports.io/football/teams/7056.png",
    "awayLogo": "https://media.api-sports.io/football/teams/2765.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581356,
    "home": "Changwon City",
    "away": "Gimhae City",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 7059,
    "awayTeamId": 7076,
    "homeLogo": "https://media.api-sports.io/football/teams/7059.png",
    "awayLogo": "https://media.api-sports.io/football/teams/7076.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581838,
    "home": "Cheongju",
    "away": "Gyeongju HNP",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 7061,
    "awayTeamId": 7083,
    "homeLogo": "https://media.api-sports.io/football/teams/7061.png",
    "awayLogo": "https://media.api-sports.io/football/teams/7083.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581359,
    "home": "Hwaseong",
    "away": "Yangpyeong",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 7087,
    "awayTeamId": 7111,
    "homeLogo": "https://media.api-sports.io/football/teams/7087.png",
    "awayLogo": "https://media.api-sports.io/football/teams/7111.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581360,
    "home": "Paju Citizen",
    "away": "Gangneung City",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 7098,
    "awayTeamId": 7075,
    "homeLogo": "https://media.api-sports.io/football/teams/7098.png",
    "awayLogo": "https://media.api-sports.io/football/teams/7075.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581363,
    "home": "Ulsan Citizen",
    "away": "Seoul E-Land FC",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 7108,
    "awayTeamId": 2749,
    "homeLogo": "https://media.api-sports.io/football/teams/7108.png",
    "awayLogo": "https://media.api-sports.io/football/teams/2749.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581364,
    "home": "Yongin City",
    "away": "Dangjin Citizen",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 9171,
    "awayTeamId": 18653,
    "homeLogo": "https://media.api-sports.io/football/teams/9171.png",
    "awayLogo": "https://media.api-sports.io/football/teams/18653.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581839,
    "home": "Namyangju",
    "away": "Gimpo Citizen",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 23089,
    "awayTeamId": 7078,
    "homeLogo": "https://media.api-sports.io/football/teams/23089.png",
    "awayLogo": "https://media.api-sports.io/football/teams/7078.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581840,
    "home": "Gyeongnam FC",
    "away": "Yeoju Sejong",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 2751,
    "awayTeamId": 7112,
    "homeLogo": "https://media.api-sports.io/football/teams/2751.png",
    "awayLogo": "https://media.api-sports.io/football/teams/7112.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:30:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1581357,
    "home": "Cheonan City",
    "away": "Mokpo City",
    "league": "FA Cup",
    "leagueId": 294,
    "season": "2026",
    "round": "Round of 64",
    "country": "South-Korea",
    "flag": "https://media.api-sports.io/flags/kr.svg",
    "homeTeamId": 7060,
    "awayTeamId": 7096,
    "homeLogo": "https://media.api-sports.io/football/teams/7060.png",
    "awayLogo": "https://media.api-sports.io/football/teams/7096.png",
    "status": "NS",
    "kickoff": "2026-07-15T10:30:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1541715,
    "home": "GBK",
    "away": "Kraft",
    "league": "Kakkonen - Lohko C",
    "leagueId": 249,
    "season": "2026",
    "round": "Group C",
    "country": "Finland",
    "flag": "https://media.api-sports.io/flags/fi.svg",
    "homeTeamId": 9191,
    "awayTeamId": 9213,
    "homeLogo": "https://media.api-sports.io/football/teams/9191.png",
    "awayLogo": "https://media.api-sports.io/football/teams/9213.png",
    "status": "NS",
    "kickoff": "2026-07-15T15:30:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1586131,
    "home": "Bahrain U20",
    "away": "Palestine U20",
    "league": "Friendlies",
    "leagueId": 10,
    "season": "2026",
    "round": "Friendly International",
    "country": "World",
    "flag": null,
    "homeTeamId": 19624,
    "awayTeamId": 19630,
    "homeLogo": "https://media.api-sports.io/football/teams/19624.png",
    "awayLogo": "https://media.api-sports.io/football/teams/19630.png",
    "status": "NS",
    "kickoff": "2026-07-15T16:15:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1519403,
    "home": "Libertad",
    "away": "Tecnico Universitario",
    "league": "Liga Pro",
    "leagueId": 242,
    "season": "2026",
    "round": "Regular Season - 19",
    "country": "Ecuador",
    "flag": "https://media.api-sports.io/flags/ec.svg",
    "homeTeamId": 18762,
    "awayTeamId": 1151,
    "homeLogo": "https://media.api-sports.io/football/teams/18762.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1151.png",
    "status": "NS",
    "kickoff": "2026-07-15T17:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554388,
    "home": "Universitatea Craiova",
    "away": "ML Vitebsk",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 632,
    "awayTeamId": 7808,
    "homeLogo": "https://media.api-sports.io/football/teams/632.png",
    "awayLogo": "https://media.api-sports.io/football/teams/7808.png",
    "status": "NS",
    "kickoff": "2026-07-15T17:30:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554375,
    "home": "Atert Bissen",
    "away": "KI Klaksvik",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 15847,
    "awayTeamId": 701,
    "homeLogo": "https://media.api-sports.io/football/teams/15847.png",
    "awayLogo": "https://media.api-sports.io/football/teams/701.png",
    "status": "NS",
    "kickoff": "2026-07-15T18:15:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554386,
    "home": "Sutjeska",
    "away": "Kairat Almaty",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 673,
    "awayTeamId": 664,
    "homeLogo": "https://media.api-sports.io/football/teams/673.png",
    "awayLogo": "https://media.api-sports.io/football/teams/664.png",
    "status": "NS",
    "kickoff": "2026-07-15T19:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1554377,
    "home": "Egnatia Rrogozhin\u00eb",
    "away": "Petrocub",
    "league": "UEFA Champions League",
    "leagueId": 2,
    "season": "2026",
    "round": "1st Qualifying Round",
    "country": "World",
    "flag": null,
    "homeTeamId": 3327,
    "awayTeamId": 2271,
    "homeLogo": "https://media.api-sports.io/football/teams/3327.png",
    "awayLogo": "https://media.api-sports.io/football/teams/2271.png",
    "status": "NS",
    "kickoff": "2026-07-15T19:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1586077,
    "home": "England",
    "away": "Argentina",
    "league": "World Cup",
    "leagueId": 1,
    "season": "2026",
    "round": "Semi-finals",
    "country": "World",
    "flag": null,
    "homeTeamId": 10,
    "awayTeamId": 26,
    "homeLogo": "https://media.api-sports.io/football/teams/10.png",
    "awayLogo": "https://media.api-sports.io/football/teams/26.png",
    "status": "NS",
    "kickoff": "2026-07-15T19:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1526576,
    "home": "Cuniburo",
    "away": "El Nacional",
    "league": "Liga Pro Serie B",
    "leagueId": 243,
    "season": "2026",
    "round": "Regular Season - 17",
    "country": "Ecuador",
    "flag": "https://media.api-sports.io/flags/ec.svg",
    "homeTeamId": 21103,
    "awayTeamId": 1150,
    "homeLogo": "https://media.api-sports.io/football/teams/21103.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1150.png",
    "status": "NS",
    "kickoff": "2026-07-15T19:30:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1519407,
    "home": "Universidad Catolica",
    "away": "LDU de Quito",
    "league": "Liga Pro",
    "leagueId": 242,
    "season": "2026",
    "round": "Regular Season - 19",
    "country": "Ecuador",
    "flag": "https://media.api-sports.io/flags/ec.svg",
    "homeTeamId": 1157,
    "awayTeamId": 1158,
    "homeLogo": "https://media.api-sports.io/football/teams/1157.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1158.png",
    "status": "NS",
    "kickoff": "2026-07-15T22:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1519402,
    "home": "Leones del Norte",
    "away": "Deportivo Cuenca",
    "league": "Liga Pro",
    "leagueId": 242,
    "season": "2026",
    "round": "Regular Season - 19",
    "country": "Ecuador",
    "flag": "https://media.api-sports.io/flags/ec.svg",
    "homeTeamId": 19034,
    "awayTeamId": 1154,
    "homeLogo": "https://media.api-sports.io/football/teams/19034.png",
    "awayLogo": "https://media.api-sports.io/football/teams/1154.png",
    "status": "NS",
    "kickoff": "2026-07-15T22:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1538388,
    "home": "Real Potos\u00ed",
    "away": "San Antonio Bulo Bulo",
    "league": "Primera Divisi\u00f3n",
    "leagueId": 344,
    "season": "2026",
    "round": "Apertura - 8",
    "country": "Bolivia",
    "flag": "https://media.api-sports.io/flags/bo.svg",
    "homeTeamId": 3708,
    "awayTeamId": 17760,
    "homeLogo": "https://media.api-sports.io/football/teams/3708.png",
    "awayLogo": "https://media.api-sports.io/football/teams/17760.png",
    "status": "NS",
    "kickoff": "2026-07-15T22:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1508466,
    "home": "Orlando Pride W",
    "away": "Boston Legacy W",
    "league": "NWSL Women",
    "leagueId": 254,
    "season": "2026",
    "round": "Group Stage",
    "country": "USA",
    "flag": "https://media.api-sports.io/flags/us.svg",
    "homeTeamId": 3000,
    "awayTeamId": 27377,
    "homeLogo": "https://media.api-sports.io/football/teams/3000.png",
    "awayLogo": "https://media.api-sports.io/football/teams/27377.png",
    "status": "NS",
    "kickoff": "2026-07-15T23:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1493574,
    "home": "Miami FC",
    "away": "Indy Eleven",
    "league": "USL Championship",
    "leagueId": 255,
    "season": "2026",
    "round": "Group Stage",
    "country": "USA",
    "flag": "https://media.api-sports.io/flags/us.svg",
    "homeTeamId": 9030,
    "awayTeamId": 3996,
    "homeLogo": "https://media.api-sports.io/football/teams/9030.png",
    "awayLogo": "https://media.api-sports.io/football/teams/3996.png",
    "status": "NS",
    "kickoff": "2026-07-15T23:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1493573,
    "home": "Lexington",
    "away": "New Mexico United",
    "league": "USL Championship",
    "leagueId": 255,
    "season": "2026",
    "round": "Group Stage",
    "country": "USA",
    "flag": "https://media.api-sports.io/flags/us.svg",
    "homeTeamId": 20808,
    "awayTeamId": 4003,
    "homeLogo": "https://media.api-sports.io/football/teams/20808.png",
    "awayLogo": "https://media.api-sports.io/football/teams/4003.png",
    "status": "NS",
    "kickoff": "2026-07-15T23:00:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  },
  {
    "id": 1493575,
    "home": "Sporting JAX",
    "away": "Pittsburgh Riverhounds",
    "league": "USL Championship",
    "leagueId": 255,
    "season": "2026",
    "round": "Group Stage",
    "country": "USA",
    "flag": "https://media.api-sports.io/flags/us.svg",
    "homeTeamId": 25959,
    "awayTeamId": 4010,
    "homeLogo": "https://media.api-sports.io/football/teams/25959.png",
    "awayLogo": "https://media.api-sports.io/football/teams/4010.png",
    "status": "NS",
    "kickoff": "2026-07-15T23:30:00+00:00",
    "matchDate": "2026-07-15",
    "homeGoals": null,
    "awayGoals": null,
    "htHome": null,
    "htAway": null,
    "fixtureOnly": true,
    "analysisPending": true,
    "enrichmentStatus": "fixture-only",
    "dataCoverage": 0
  }
];
