-- Predict2U v189 — Global Football News, transfers, comments and push alerts.
-- Run AFTER v180 Accounts, v181 Backend Admin and v183 Push in the same project.
-- Public clients use the Supabase publishable key. Feed ingestion uses service_role
-- from the protected p2u-news-sync Edge Function.

begin;

create table if not exists public.p2u_news_sources (
  id bigint generated by default as identity primary key,
  name text not null,
  feed_url text not null unique,
  homepage_url text not null default '',
  region text not null default 'Global',
  enabled boolean not null default true,
  priority integer not null default 100,
  last_success_at timestamptz null,
  last_error text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Starter RSS sources. These rows are editable; the sync function skips a source
-- cleanly if a publisher changes or removes its feed URL.
insert into public.p2u_news_sources(name,feed_url,homepage_url,region,priority)
values
  ('BBC Sport Football','https://feeds.bbci.co.uk/sport/football/rss.xml','https://www.bbc.com/sport/football','Global',10),
  ('The Guardian Football','https://www.theguardian.com/football/rss','https://www.theguardian.com/football','Global',20),
  ('Sky Sports Football','https://www.skysports.com/rss/12040','https://www.skysports.com/football','Europe',30),
  ('ESPN Soccer','https://www.espn.com/espn/rss/soccer/news','https://www.espn.com/soccer/','Global',40)
on conflict(feed_url) do nothing;

alter table public.p2u_news_sources enable row level security;
drop policy if exists "Public reads enabled news sources" on public.p2u_news_sources;
create policy "Public reads enabled news sources" on public.p2u_news_sources
for select to anon,authenticated using(enabled=true or public.p2u_has_admin_role(array['owner','admin']));
drop policy if exists "Admins manage news sources" on public.p2u_news_sources;
create policy "Admins manage news sources" on public.p2u_news_sources
for all to authenticated
using(public.p2u_has_admin_role(array['owner','admin']))
with check(public.p2u_has_admin_role(array['owner','admin']));

create table if not exists public.p2u_news_articles (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  source_id bigint null references public.p2u_news_sources(id) on delete set null,
  source_name text not null,
  source_domain text not null default '',
  title text not null,
  summary text not null default '',
  url text not null unique,
  image_url text not null default '',
  category text not null default 'news' check(category in ('news','transfer')),
  region text not null default 'Global',
  league text not null default '',
  club text not null default '',
  player text not null default '',
  breaking boolean not null default false,
  published boolean not null default true,
  push_eligible boolean not null default false,
  published_at timestamptz not null default now(),
  comment_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists p2u_news_articles_feed_idx on public.p2u_news_articles(published,published_at desc);
create index if not exists p2u_news_articles_category_idx on public.p2u_news_articles(category,published_at desc);
create index if not exists p2u_news_articles_source_idx on public.p2u_news_articles(source_id,published_at desc);

alter table public.p2u_news_articles enable row level security;
drop policy if exists "Public reads published football news" on public.p2u_news_articles;
create policy "Public reads published football news" on public.p2u_news_articles
for select to anon,authenticated using(published=true or public.p2u_has_admin_role(array['owner','admin','moderator']));
drop policy if exists "Admins manage football news" on public.p2u_news_articles;
create policy "Admins manage football news" on public.p2u_news_articles
for all to authenticated
using(public.p2u_has_admin_role(array['owner','admin','moderator']))
with check(public.p2u_has_admin_role(array['owner','admin','moderator']));

create table if not exists public.p2u_news_comments (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.p2u_news_articles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  handle_snapshot text not null default 'member',
  body text not null check(char_length(body) between 1 and 600),
  status text not null default 'visible' check(status in ('visible','hidden','review')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists p2u_news_comments_article_idx on public.p2u_news_comments(article_id,created_at);
create index if not exists p2u_news_comments_user_idx on public.p2u_news_comments(user_id,created_at desc);

alter table public.p2u_news_comments enable row level security;
drop policy if exists "Public reads visible news comments" on public.p2u_news_comments;
create policy "Public reads visible news comments" on public.p2u_news_comments
for select to anon,authenticated
using(status='visible' or user_id=auth.uid() or public.p2u_has_admin_role(array['owner','admin','moderator']));
drop policy if exists "Users delete own news comments" on public.p2u_news_comments;
create policy "Users delete own news comments" on public.p2u_news_comments
for delete to authenticated using(user_id=auth.uid());
drop policy if exists "Moderators manage news comments" on public.p2u_news_comments;
create policy "Moderators manage news comments" on public.p2u_news_comments
for update to authenticated
using(public.p2u_has_admin_role(array['owner','admin','moderator']))
with check(public.p2u_has_admin_role(array['owner','admin','moderator']));

create or replace function public.p2u_news_post_comment(p_article_id bigint,p_body text)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare clean_body text:=trim(regexp_replace(coalesce(p_body,''),'\s+',' ','g'));
declare handle_value text:='member';
declare row_out public.p2u_news_comments%rowtype;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  if char_length(clean_body)<1 or char_length(clean_body)>600 then raise exception 'Comment must be 1 to 600 characters'; end if;
  if not exists(select 1 from public.p2u_news_articles where id=p_article_id and published=true) then raise exception 'News article not found'; end if;
  select left(coalesce(nullif(handle,''),'member'),50) into handle_value from public.profiles where id=auth.uid();
  insert into public.p2u_news_comments(article_id,user_id,handle_snapshot,body)
  values(p_article_id,auth.uid(),coalesce(handle_value,'member'),clean_body)
  returning * into row_out;
  return to_jsonb(row_out);
end;
$$;
revoke all on function public.p2u_news_post_comment(bigint,text) from public;
grant execute on function public.p2u_news_post_comment(bigint,text) to authenticated;

create or replace function public.p2u_news_update_comment_count()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare affected_id bigint;
begin
  affected_id:=case when tg_op='DELETE' then old.article_id else new.article_id end;
  update public.p2u_news_articles
  set comment_count=(select count(*) from public.p2u_news_comments where article_id=affected_id and status='visible'),updated_at=now()
  where id=affected_id;
  if tg_op='DELETE' then return old; end if;
  return new;
end;
$$;
drop trigger if exists p2u_news_comment_count_trigger on public.p2u_news_comments;
create trigger p2u_news_comment_count_trigger
after insert or update or delete on public.p2u_news_comments
for each row execute function public.p2u_news_update_comment_count();

-- Add independent news push preferences.
alter table public.p2u_push_preferences add column if not exists football_news boolean not null default true;
alter table public.p2u_push_preferences add column if not exists transfer_news boolean not null default true;

-- Extend the push category list with news.
alter table public.p2u_push_jobs drop constraint if exists p2u_push_jobs_category_check;
alter table public.p2u_push_jobs add constraint p2u_push_jobs_category_check
check(category in ('board','match','community','announcement','system','test','news'));

create or replace function public.p2u_save_push_preferences(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare row_out public.p2u_push_preferences%rowtype;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  insert into public.p2u_push_preferences(
    user_id,enabled,board_updates,match_status,favorite_leagues,favorite_engines,community_wins,
    followed_users,announcements,verified_only,football_news,transfer_news,quiet_enabled,quiet_start,quiet_end,timezone,
    timezone_offset_minutes,favorite_league_names,favorite_engine_names,followed_user_ids,updated_at
  ) values (
    auth.uid(),coalesce((p_payload->>'enabled')::boolean,true),coalesce((p_payload->>'board_updates')::boolean,true),
    coalesce((p_payload->>'match_status')::boolean,true),coalesce((p_payload->>'favorite_leagues')::boolean,true),
    coalesce((p_payload->>'favorite_engines')::boolean,true),coalesce((p_payload->>'community_wins')::boolean,true),
    coalesce((p_payload->>'followed_users')::boolean,false),coalesce((p_payload->>'announcements')::boolean,true),
    coalesce((p_payload->>'verified_only')::boolean,false),coalesce((p_payload->>'football_news')::boolean,true),
    coalesce((p_payload->>'transfer_news')::boolean,true),coalesce((p_payload->>'quiet_enabled')::boolean,false),
    coalesce(nullif(p_payload->>'quiet_start','')::time,'22:00'::time),coalesce(nullif(p_payload->>'quiet_end','')::time,'07:00'::time),
    left(coalesce(nullif(p_payload->>'timezone',''),'UTC'),80),greatest(-840,least(840,coalesce((p_payload->>'timezone_offset_minutes')::integer,0))),
    coalesce((select array_agg(left(value,120)) from (select value from jsonb_array_elements_text(coalesce(p_payload->'favorite_league_names','[]'::jsonb)) limit 80)x),'{}'::text[]),
    coalesce((select array_agg(left(value,80)) from (select value from jsonb_array_elements_text(coalesce(p_payload->'favorite_engine_names','[]'::jsonb)) limit 40)x),'{}'::text[]),
    coalesce((select array_agg(value::uuid) from (select value from jsonb_array_elements_text(coalesce(p_payload->'followed_user_ids','[]'::jsonb)) where value~*'^[0-9a-f-]{36}$' limit 500)x),'{}'::uuid[]),now()
  )
  on conflict(user_id) do update set
    enabled=excluded.enabled,board_updates=excluded.board_updates,match_status=excluded.match_status,
    favorite_leagues=excluded.favorite_leagues,favorite_engines=excluded.favorite_engines,community_wins=excluded.community_wins,
    followed_users=excluded.followed_users,announcements=excluded.announcements,verified_only=excluded.verified_only,
    football_news=excluded.football_news,transfer_news=excluded.transfer_news,quiet_enabled=excluded.quiet_enabled,
    quiet_start=excluded.quiet_start,quiet_end=excluded.quiet_end,timezone=excluded.timezone,
    timezone_offset_minutes=excluded.timezone_offset_minutes,favorite_league_names=excluded.favorite_league_names,
    favorite_engine_names=excluded.favorite_engine_names,followed_user_ids=excluded.followed_user_ids,updated_at=now()
  returning * into row_out;
  return to_jsonb(row_out);
end;
$$;
revoke all on function public.p2u_save_push_preferences(jsonb) from public;
grant execute on function public.p2u_save_push_preferences(jsonb) to authenticated;

-- Transfer and breaking stories create background push jobs. General stories stay
-- in the News tab and in-app feed to avoid excessive notification volume.
create or replace function public.p2u_push_from_news_article()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if new.published=true and new.push_eligible=true then
    insert into public.p2u_push_jobs(category,title,body,url,audience,payload,scheduled_for)
    values(
      'news',
      case when new.category='transfer' then 'Transfer update' when new.breaking then 'Breaking football news' else 'Football news' end,
      left(new.title,240),
      'news.html?article='||new.id::text,
      jsonb_build_object('type','all'),
      jsonb_build_object('article_id',new.id,'news_type',new.category,'source',new.source_name,'breaking',new.breaking),
      now()
    );
  end if;
  return new;
end;
$$;
drop trigger if exists p2u_news_push_trigger on public.p2u_news_articles;
create trigger p2u_news_push_trigger
after insert on public.p2u_news_articles
for each row execute function public.p2u_push_from_news_article();

commit;
