-- Predict2U v192 — News Personalization, Trust & Moderation
-- Run after SUPABASE_FOOTBALL_NEWS_v189.sql.
-- Adds followed topics, Read Later, source verification, reporting, moderation,
-- personalized news push preferences and server-side spam safeguards.

begin;

alter table public.p2u_news_sources
  add column if not exists verified boolean not null default false,
  add column if not exists trust_note text not null default '';

update public.p2u_news_sources
set verified=true,
    trust_note=case
      when trust_note='' then 'Known publisher feed reviewed by Predict2U.'
      else trust_note
    end
where name in ('BBC Sport Football','The Guardian Football','Sky Sports Football','ESPN Soccer');

alter table public.p2u_news_articles
  add column if not exists source_verified boolean not null default false,
  add column if not exists canonical_key text not null default '',
  add column if not exists featured boolean not null default false,
  add column if not exists pinned boolean not null default false,
  add column if not exists moderation_status text not null default 'visible',
  add column if not exists moderation_reason text not null default '';

alter table public.p2u_news_articles drop constraint if exists p2u_news_articles_moderation_status_check;
alter table public.p2u_news_articles add constraint p2u_news_articles_moderation_status_check
check(moderation_status in ('visible','review','hidden'));

update public.p2u_news_articles a
set source_verified=coalesce(s.verified,false)
from public.p2u_news_sources s
where a.source_id=s.id and a.source_verified is distinct from coalesce(s.verified,false);

update public.p2u_news_articles
set canonical_key=left(
  regexp_replace(
    regexp_replace(lower(title),'[^a-z0-9 ]','','g'),
    '\m(the|a|an|to|for|of|in|on|at|with|and|or|from|after|before|latest|breaking|official|confirmed)\M',
    '',
    'g'
  ),
  180
)
where canonical_key='';

create index if not exists p2u_news_articles_canonical_idx on public.p2u_news_articles(canonical_key,published_at desc);
create index if not exists p2u_news_articles_featured_idx on public.p2u_news_articles(pinned desc,featured desc,published_at desc);
create index if not exists p2u_news_articles_moderation_idx on public.p2u_news_articles(moderation_status,published_at desc);

-- Tighten public visibility so hidden/review stories do not appear publicly.
drop policy if exists "Public reads published football news" on public.p2u_news_articles;
create policy "Public reads published football news" on public.p2u_news_articles
for select to anon,authenticated
using(
  (published=true and moderation_status='visible')
  or public.p2u_has_admin_role(array['owner','admin','moderator'])
);

create table if not exists public.p2u_news_follows (
  user_id uuid not null references auth.users(id) on delete cascade,
  entity_type text not null check(entity_type in ('club','league','country','player','source','topic')),
  entity_value text not null,
  normalized_value text generated always as (lower(trim(entity_value))) stored,
  created_at timestamptz not null default now(),
  primary key(user_id,entity_type,normalized_value)
);
create index if not exists p2u_news_follows_user_idx on public.p2u_news_follows(user_id,created_at desc);
alter table public.p2u_news_follows enable row level security;
drop policy if exists "Users read own news follows" on public.p2u_news_follows;
create policy "Users read own news follows" on public.p2u_news_follows
for select to authenticated using(user_id=auth.uid());
drop policy if exists "Users manage own news follows" on public.p2u_news_follows;
create policy "Users manage own news follows" on public.p2u_news_follows
for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

create table if not exists public.p2u_news_bookmarks (
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id bigint not null references public.p2u_news_articles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,article_id)
);
create index if not exists p2u_news_bookmarks_user_idx on public.p2u_news_bookmarks(user_id,created_at desc);
alter table public.p2u_news_bookmarks enable row level security;
drop policy if exists "Users read own news bookmarks" on public.p2u_news_bookmarks;
create policy "Users read own news bookmarks" on public.p2u_news_bookmarks
for select to authenticated using(user_id=auth.uid());
drop policy if exists "Users manage own news bookmarks" on public.p2u_news_bookmarks;
create policy "Users manage own news bookmarks" on public.p2u_news_bookmarks
for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

create table if not exists public.p2u_news_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  article_id bigint null references public.p2u_news_articles(id) on delete cascade,
  comment_id bigint null references public.p2u_news_comments(id) on delete cascade,
  reason text not null check(reason in ('spam','abuse','misleading','copyright','privacy','other')),
  details text not null default '',
  status text not null default 'pending' check(status in ('pending','reviewing','actioned','dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz null,
  reviewed_by uuid null references auth.users(id) on delete set null,
  constraint p2u_news_reports_one_target check((article_id is not null)::int + (comment_id is not null)::int = 1)
);
create index if not exists p2u_news_reports_status_idx on public.p2u_news_reports(status,created_at desc);
create index if not exists p2u_news_reports_reporter_idx on public.p2u_news_reports(reporter_id,created_at desc);
alter table public.p2u_news_reports enable row level security;
drop policy if exists "Users read own news reports" on public.p2u_news_reports;
create policy "Users read own news reports" on public.p2u_news_reports
for select to authenticated
using(reporter_id=auth.uid() or public.p2u_has_admin_role(array['owner','admin','moderator']));
drop policy if exists "Moderators manage news reports" on public.p2u_news_reports;
create policy "Moderators manage news reports" on public.p2u_news_reports
for update to authenticated
using(public.p2u_has_admin_role(array['owner','admin','moderator']))
with check(public.p2u_has_admin_role(array['owner','admin','moderator']));

create or replace function public.p2u_news_toggle_follow(p_entity_type text,p_entity_value text)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare kind text:=lower(trim(coalesce(p_entity_type,'')));
declare value_clean text:=left(trim(regexp_replace(coalesce(p_entity_value,''),'\s+',' ','g')),100);
declare was_following boolean;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  if kind not in ('club','league','country','player','source','topic') then raise exception 'Unsupported follow type'; end if;
  if char_length(value_clean)<2 then raise exception 'Follow topic is too short'; end if;
  select exists(select 1 from public.p2u_news_follows where user_id=auth.uid() and entity_type=kind and normalized_value=lower(value_clean)) into was_following;
  if was_following then
    delete from public.p2u_news_follows where user_id=auth.uid() and entity_type=kind and normalized_value=lower(value_clean);
    return jsonb_build_object('following',false,'entity_type',kind,'entity_value',value_clean);
  end if;
  insert into public.p2u_news_follows(user_id,entity_type,entity_value)
  values(auth.uid(),kind,value_clean)
  on conflict do nothing;
  return jsonb_build_object('following',true,'entity_type',kind,'entity_value',value_clean);
end;
$$;
revoke all on function public.p2u_news_toggle_follow(text,text) from public;
grant execute on function public.p2u_news_toggle_follow(text,text) to authenticated;

create or replace function public.p2u_news_toggle_bookmark(p_article_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare exists_now boolean;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  if not exists(select 1 from public.p2u_news_articles where id=p_article_id and published=true and moderation_status='visible') then raise exception 'News article not found'; end if;
  select exists(select 1 from public.p2u_news_bookmarks where user_id=auth.uid() and article_id=p_article_id) into exists_now;
  if exists_now then
    delete from public.p2u_news_bookmarks where user_id=auth.uid() and article_id=p_article_id;
    return jsonb_build_object('saved',false,'article_id',p_article_id);
  end if;
  insert into public.p2u_news_bookmarks(user_id,article_id) values(auth.uid(),p_article_id) on conflict do nothing;
  return jsonb_build_object('saved',true,'article_id',p_article_id);
end;
$$;
revoke all on function public.p2u_news_toggle_bookmark(bigint) from public;
grant execute on function public.p2u_news_toggle_bookmark(bigint) to authenticated;

create or replace function public.p2u_news_report(
  p_article_id bigint default null,
  p_comment_id bigint default null,
  p_reason text default 'other',
  p_details text default ''
)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare reason_clean text:=lower(trim(coalesce(p_reason,'other')));
declare details_clean text:=left(trim(regexp_replace(coalesce(p_details,''),'\s+',' ','g')),500);
declare row_id bigint;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  if ((p_article_id is not null)::int + (p_comment_id is not null)::int) <> 1 then raise exception 'Choose one report target'; end if;
  if reason_clean not in ('spam','abuse','misleading','copyright','privacy','other') then reason_clean:='other'; end if;
  if (select count(*) from public.p2u_news_reports where reporter_id=auth.uid() and created_at>now()-interval '1 hour')>=8 then raise exception 'Too many reports. Try again later.'; end if;
  if p_article_id is not null and not exists(select 1 from public.p2u_news_articles where id=p_article_id) then raise exception 'Article not found'; end if;
  if p_comment_id is not null and not exists(select 1 from public.p2u_news_comments where id=p_comment_id) then raise exception 'Comment not found'; end if;
  insert into public.p2u_news_reports(reporter_id,article_id,comment_id,reason,details)
  values(auth.uid(),p_article_id,p_comment_id,reason_clean,details_clean)
  returning id into row_id;
  return jsonb_build_object('ok',true,'report_id',row_id);
end;
$$;
revoke all on function public.p2u_news_report(bigint,bigint,text,text) from public;
grant execute on function public.p2u_news_report(bigint,bigint,text,text) to authenticated;

-- Replace comment posting with rate limits, duplicate prevention and basic spam checks.
create or replace function public.p2u_news_post_comment(p_article_id bigint,p_body text)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare clean_body text:=trim(regexp_replace(coalesce(p_body,''),'\s+',' ','g'));
declare handle_value text:='member';
declare row_out public.p2u_news_comments%rowtype;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  if char_length(clean_body)<2 or char_length(clean_body)>600 then raise exception 'Comment must be 2 to 600 characters'; end if;
  if not exists(select 1 from public.p2u_news_articles where id=p_article_id and published=true and moderation_status='visible') then raise exception 'News article not found'; end if;
  if (select count(*) from public.p2u_news_comments where user_id=auth.uid() and created_at>now()-interval '10 minutes')>=10 then raise exception 'Comment limit reached. Try again shortly.'; end if;
  if exists(select 1 from public.p2u_news_comments where user_id=auth.uid() and article_id=p_article_id and lower(body)=lower(clean_body) and created_at>now()-interval '1 hour') then raise exception 'Duplicate comment'; end if;
  if clean_body ~* '(https?://[^ ]+.*https?://|telegram|whatsapp me|guaranteed win|free money|dm me for|contact me on|(.)\1{11,})' then raise exception 'Comment looks like spam'; end if;
  select left(coalesce(nullif(handle,''),'member'),50) into handle_value from public.profiles where id=auth.uid();
  insert into public.p2u_news_comments(article_id,user_id,handle_snapshot,body)
  values(p_article_id,auth.uid(),coalesce(handle_value,'member'),clean_body)
  returning * into row_out;
  return to_jsonb(row_out);
end;
$$;
revoke all on function public.p2u_news_post_comment(bigint,text) from public;
grant execute on function public.p2u_news_post_comment(bigint,text) to authenticated;

create or replace function public.p2u_admin_news_action(
  p_article_id bigint,
  p_action text,
  p_value boolean default true,
  p_reason text default ''
)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare action_clean text:=lower(trim(coalesce(p_action,'')));
declare reason_clean text:=left(trim(coalesce(p_reason,'')),500);
declare role_value text;
declare row_out public.p2u_news_articles%rowtype;
begin
  select role into role_value from public.p2u_admin_roles where user_id=auth.uid() and active=true;
  if role_value not in ('owner','admin','moderator') then raise exception 'Admin role required' using errcode='42501'; end if;
  if action_clean='feature' then
    update public.p2u_news_articles set featured=p_value,updated_at=now() where id=p_article_id returning * into row_out;
  elsif action_clean='pin' then
    update public.p2u_news_articles set pinned=p_value,updated_at=now() where id=p_article_id returning * into row_out;
  elsif action_clean='breaking' then
    update public.p2u_news_articles set breaking=p_value,push_eligible=(push_eligible or p_value),updated_at=now() where id=p_article_id returning * into row_out;
  elsif action_clean='hide' then
    update public.p2u_news_articles set moderation_status=case when p_value then 'hidden' else 'visible' end,moderation_reason=reason_clean,published=not p_value,updated_at=now() where id=p_article_id returning * into row_out;
  elsif action_clean='review' then
    update public.p2u_news_articles set moderation_status=case when p_value then 'review' else 'visible' end,moderation_reason=reason_clean,updated_at=now() where id=p_article_id returning * into row_out;
  elsif action_clean='publish' then
    update public.p2u_news_articles set published=p_value,moderation_status=case when p_value then 'visible' else moderation_status end,updated_at=now() where id=p_article_id returning * into row_out;
  else
    raise exception 'Unsupported news action';
  end if;
  if row_out.id is null then raise exception 'Article not found'; end if;
  insert into public.p2u_admin_audit_log(actor_id,actor_role,action,target_type,target_key,metadata)
  values(auth.uid(),role_value,'news_'||action_clean,'news_article',p_article_id::text,jsonb_build_object('value',p_value,'reason',reason_clean));
  return to_jsonb(row_out);
end;
$$;
revoke all on function public.p2u_admin_news_action(bigint,text,boolean,text) from public;
grant execute on function public.p2u_admin_news_action(bigint,text,boolean,text) to authenticated;

create or replace function public.p2u_admin_news_resolve_report(
  p_report_id bigint,
  p_status text,
  p_hide_target boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare status_clean text:=lower(trim(coalesce(p_status,'')));
declare role_value text;
declare report_row public.p2u_news_reports%rowtype;
begin
  select role into role_value from public.p2u_admin_roles where user_id=auth.uid() and active=true;
  if role_value not in ('owner','admin','moderator') then raise exception 'Admin role required' using errcode='42501'; end if;
  if status_clean not in ('reviewing','actioned','dismissed') then raise exception 'Unsupported report status'; end if;
  select * into report_row from public.p2u_news_reports where id=p_report_id for update;
  if report_row.id is null then raise exception 'Report not found'; end if;
  update public.p2u_news_reports set status=status_clean,reviewed_at=now(),reviewed_by=auth.uid() where id=p_report_id;
  if p_hide_target and report_row.article_id is not null then
    update public.p2u_news_articles set published=false,moderation_status='hidden',moderation_reason='Hidden from report #'||p_report_id::text,updated_at=now() where id=report_row.article_id;
  elsif p_hide_target and report_row.comment_id is not null then
    update public.p2u_news_comments set status='hidden',updated_at=now() where id=report_row.comment_id;
  end if;
  insert into public.p2u_admin_audit_log(actor_id,actor_role,action,target_type,target_key,metadata)
  values(auth.uid(),role_value,'news_report_'||status_clean,'news_report',p_report_id::text,jsonb_build_object('hide_target',p_hide_target));
  return jsonb_build_object('ok',true,'report_id',p_report_id,'status',status_clean,'target_hidden',p_hide_target);
end;
$$;
revoke all on function public.p2u_admin_news_resolve_report(bigint,text,boolean) from public;
grant execute on function public.p2u_admin_news_resolve_report(bigint,text,boolean) to authenticated;

-- Detailed news notification preferences.
alter table public.p2u_push_preferences add column if not exists breaking_news boolean not null default true;
alter table public.p2u_push_preferences add column if not exists personalized_news boolean not null default false;
alter table public.p2u_push_preferences add column if not exists news_topics text[] not null default '{}'::text[];

create or replace function public.p2u_save_push_preferences(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare row_out public.p2u_push_preferences%rowtype;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  insert into public.p2u_push_preferences(
    user_id,enabled,board_updates,match_status,favorite_leagues,favorite_engines,community_wins,
    followed_users,announcements,verified_only,football_news,transfer_news,breaking_news,personalized_news,news_topics,
    quiet_enabled,quiet_start,quiet_end,timezone,timezone_offset_minutes,favorite_league_names,favorite_engine_names,
    followed_user_ids,updated_at
  ) values (
    auth.uid(),coalesce((p_payload->>'enabled')::boolean,true),coalesce((p_payload->>'board_updates')::boolean,true),
    coalesce((p_payload->>'match_status')::boolean,true),coalesce((p_payload->>'favorite_leagues')::boolean,true),
    coalesce((p_payload->>'favorite_engines')::boolean,true),coalesce((p_payload->>'community_wins')::boolean,true),
    coalesce((p_payload->>'followed_users')::boolean,false),coalesce((p_payload->>'announcements')::boolean,true),
    coalesce((p_payload->>'verified_only')::boolean,false),coalesce((p_payload->>'football_news')::boolean,true),
    coalesce((p_payload->>'transfer_news')::boolean,true),coalesce((p_payload->>'breaking_news')::boolean,true),
    coalesce((p_payload->>'personalized_news')::boolean,false),
    coalesce((select array_agg(left(value,100)) from (select value from jsonb_array_elements_text(coalesce(p_payload->'news_topics','[]'::jsonb)) limit 100)x),'{}'::text[]),
    coalesce((p_payload->>'quiet_enabled')::boolean,false),
    coalesce(nullif(p_payload->>'quiet_start','')::time,'22:00'::time),
    coalesce(nullif(p_payload->>'quiet_end','')::time,'07:00'::time),
    left(coalesce(nullif(p_payload->>'timezone',''),'UTC'),80),
    greatest(-840,least(840,coalesce((p_payload->>'timezone_offset_minutes')::integer,0))),
    coalesce((select array_agg(left(value,120)) from (select value from jsonb_array_elements_text(coalesce(p_payload->'favorite_league_names','[]'::jsonb)) limit 80)x),'{}'::text[]),
    coalesce((select array_agg(left(value,80)) from (select value from jsonb_array_elements_text(coalesce(p_payload->'favorite_engine_names','[]'::jsonb)) limit 40)x),'{}'::text[]),
    coalesce((select array_agg(value::uuid) from (select value from jsonb_array_elements_text(coalesce(p_payload->'followed_user_ids','[]'::jsonb)) where value~*'^[0-9a-f-]{36}$' limit 500)x),'{}'::uuid[]),
    now()
  )
  on conflict(user_id) do update set
    enabled=excluded.enabled,board_updates=excluded.board_updates,match_status=excluded.match_status,
    favorite_leagues=excluded.favorite_leagues,favorite_engines=excluded.favorite_engines,community_wins=excluded.community_wins,
    followed_users=excluded.followed_users,announcements=excluded.announcements,verified_only=excluded.verified_only,
    football_news=excluded.football_news,transfer_news=excluded.transfer_news,breaking_news=excluded.breaking_news,
    personalized_news=excluded.personalized_news,news_topics=excluded.news_topics,
    quiet_enabled=excluded.quiet_enabled,quiet_start=excluded.quiet_start,quiet_end=excluded.quiet_end,
    timezone=excluded.timezone,timezone_offset_minutes=excluded.timezone_offset_minutes,
    favorite_league_names=excluded.favorite_league_names,favorite_engine_names=excluded.favorite_engine_names,
    followed_user_ids=excluded.followed_user_ids,updated_at=now()
  returning * into row_out;
  return to_jsonb(row_out);
end;
$$;
revoke all on function public.p2u_save_push_preferences(jsonb) from public;
grant execute on function public.p2u_save_push_preferences(jsonb) to authenticated;

-- Replace news push trigger with richer targeting metadata and explanations.
create or replace function public.p2u_push_from_news_article()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare search_text text;
begin
  search_text:=lower(concat_ws(' ',new.title,new.summary,new.source_name,new.region,new.league,new.club,new.player));
  if new.published=true and new.moderation_status='visible' and new.push_eligible=true then
    insert into public.p2u_push_jobs(category,title,body,url,audience,payload,scheduled_for)
    values(
      'news',
      case when new.category='transfer' then 'Transfer update' when new.breaking then 'Breaking football news' else 'Football news' end,
      left(new.title,240),
      'news.html?article='||new.id::text,
      jsonb_build_object('type','all'),
      jsonb_build_object(
        'article_id',new.id,
        'news_type',new.category,
        'source',new.source_name,
        'source_verified',new.source_verified,
        'breaking',new.breaking,
        'region',new.region,
        'league',new.league,
        'club',new.club,
        'player',new.player,
        'search_text',left(search_text,1200)
      ),
      now()
    );
  end if;
  return new;
end;
$$;

commit;
