-- Predict2U v181 — Real Backend Admin
-- Run in the SAME Supabase project already used by v180 Accounts and Community.
-- IMPORTANT: replace YOUR_ACCOUNT_EMAIL@example.com near the end before running.
-- The browser continues to use only the publishable key. RLS and RPC checks protect admin actions.

begin;

create table if not exists public.p2u_admin_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','admin','moderator')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid null references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id) on delete set null
);

create or replace function public.p2u_has_admin_role(allowed_roles text[] default array['owner','admin','moderator'])
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1 from public.p2u_admin_roles r
    where r.user_id = auth.uid()
      and r.active = true
      and r.role = any(allowed_roles)
  );
$$;
revoke all on function public.p2u_has_admin_role(text[]) from public;
grant execute on function public.p2u_has_admin_role(text[]) to authenticated;

alter table public.p2u_admin_roles enable row level security;
drop policy if exists "Admins read role directory" on public.p2u_admin_roles;
create policy "Admins read role directory" on public.p2u_admin_roles
for select to authenticated
using (user_id = auth.uid() or public.p2u_has_admin_role(array['owner','admin']));

create table if not exists public.p2u_site_settings (
  id text primary key default 'global',
  board_published boolean not null default true,
  board_message text not null default 'Today''s board is being prepared. Please check back shortly.',
  announcement_enabled boolean not null default false,
  announcement_tone text not null default 'info' check (announcement_tone in ('info','success','warning')),
  announcement_message text not null default '',
  announcement_link_label text not null default '',
  announcement_link_url text not null default '',
  announcement_expires_at timestamptz null,
  featured_engines text[] not null default '{}',
  featured_leagues text[] not null default '{}',
  release_version text not null default 'v181',
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id) on delete set null
);
insert into public.p2u_site_settings(id) values ('global') on conflict (id) do nothing;
alter table public.p2u_site_settings enable row level security;
drop policy if exists "Public reads site settings" on public.p2u_site_settings;
create policy "Public reads site settings" on public.p2u_site_settings
for select to anon, authenticated using (id = 'global');

create table if not exists public.p2u_community_moderation (
  slip_id text primary key,
  status text not null check (status in ('review','verified','hidden')),
  reason text not null default '',
  created_at timestamptz not null default now(),
  created_by uuid null references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id) on delete set null
);
create index if not exists p2u_community_moderation_status_idx on public.p2u_community_moderation(status, updated_at desc);
alter table public.p2u_community_moderation enable row level security;
drop policy if exists "Public reads visible moderation" on public.p2u_community_moderation;
create policy "Public reads visible moderation" on public.p2u_community_moderation
for select to anon, authenticated
using (status in ('verified','hidden') or public.p2u_has_admin_role(array['owner','admin','moderator']));

create table if not exists public.p2u_admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid null references auth.users(id) on delete set null,
  actor_role text null,
  action text not null,
  target_type text not null,
  target_key text null,
  before_state jsonb null,
  after_state jsonb null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists p2u_admin_audit_log_created_idx on public.p2u_admin_audit_log(created_at desc);
create index if not exists p2u_admin_audit_log_actor_idx on public.p2u_admin_audit_log(actor_id, created_at desc);
alter table public.p2u_admin_audit_log enable row level security;
drop policy if exists "Admins read audit log" on public.p2u_admin_audit_log;
create policy "Admins read audit log" on public.p2u_admin_audit_log
for select to authenticated
using (public.p2u_has_admin_role(array['owner','admin','moderator']));

create or replace function public.p2u_write_admin_audit(
  p_action text,
  p_target_type text,
  p_target_key text,
  p_before jsonb,
  p_after jsonb,
  p_metadata jsonb default '{}'::jsonb
) returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_role text;
begin
  select role into v_role from public.p2u_admin_roles
  where user_id = auth.uid() and active = true;
  insert into public.p2u_admin_audit_log(actor_id,actor_role,action,target_type,target_key,before_state,after_state,metadata)
  values(auth.uid(),v_role,left(coalesce(p_action,''),120),left(coalesce(p_target_type,''),80),left(coalesce(p_target_key,''),240),p_before,p_after,coalesce(p_metadata,'{}'::jsonb));
end;
$$;
revoke all on function public.p2u_write_admin_audit(text,text,text,jsonb,jsonb,jsonb) from public;

create or replace function public.p2u_admin_save_site_settings(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare before_row public.p2u_site_settings%rowtype;
declare after_row public.p2u_site_settings%rowtype;
declare clean_tone text;
begin
  if not public.p2u_has_admin_role(array['owner','admin']) then
    raise exception 'Admin role required' using errcode='42501';
  end if;
  select * into before_row from public.p2u_site_settings where id='global';
  clean_tone := case when coalesce(p_payload->>'announcement_tone','') in ('info','success','warning') then p_payload->>'announcement_tone' else 'info' end;
  update public.p2u_site_settings set
    board_published = coalesce((p_payload->>'board_published')::boolean, board_published),
    board_message = left(coalesce(p_payload->>'board_message',board_message),500),
    announcement_enabled = coalesce((p_payload->>'announcement_enabled')::boolean,announcement_enabled),
    announcement_tone = clean_tone,
    announcement_message = left(coalesce(p_payload->>'announcement_message',announcement_message),500),
    announcement_link_label = left(coalesce(p_payload->>'announcement_link_label',announcement_link_label),80),
    announcement_link_url = left(coalesce(p_payload->>'announcement_link_url',announcement_link_url),500),
    announcement_expires_at = case when nullif(p_payload->>'announcement_expires_at','') is null then null else (p_payload->>'announcement_expires_at')::timestamptz end,
    featured_engines = coalesce((select array_agg(left(value,80)) from (select value from jsonb_array_elements_text(coalesce(p_payload->'featured_engines','[]'::jsonb)) limit 20) e),'{}'::text[]),
    featured_leagues = coalesce((select array_agg(left(value,120)) from (select value from jsonb_array_elements_text(coalesce(p_payload->'featured_leagues','[]'::jsonb)) limit 40) l),'{}'::text[]),
    release_version = left(coalesce(p_payload->>'release_version','v181'),24),
    updated_at = now(),
    updated_by = auth.uid()
  where id='global'
  returning * into after_row;
  perform public.p2u_write_admin_audit('site_settings.save','site_settings','global',to_jsonb(before_row),to_jsonb(after_row),'{}'::jsonb);
  return to_jsonb(after_row);
end;
$$;
revoke all on function public.p2u_admin_save_site_settings(jsonb) from public;
grant execute on function public.p2u_admin_save_site_settings(jsonb) to authenticated;

create or replace function public.p2u_admin_moderate_community(
  p_slip_id text,
  p_status text,
  p_reason text default ''
) returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare clean_id text := left(trim(coalesce(p_slip_id,'')),240);
declare clean_status text := lower(trim(coalesce(p_status,'')));
declare before_row public.p2u_community_moderation%rowtype;
declare after_row public.p2u_community_moderation%rowtype;
begin
  if not public.p2u_has_admin_role(array['owner','admin','moderator']) then
    raise exception 'Moderator role required' using errcode='42501';
  end if;
  if clean_id = '' then raise exception 'Slip ID is required'; end if;
  select * into before_row from public.p2u_community_moderation where slip_id=clean_id;
  if clean_status = 'clear' then
    delete from public.p2u_community_moderation where slip_id=clean_id;
    perform public.p2u_write_admin_audit('community.clear','community_slip',clean_id,to_jsonb(before_row),null,'{}'::jsonb);
    return jsonb_build_object('slip_id',clean_id,'status','clear');
  end if;
  if clean_status not in ('review','verified','hidden') then raise exception 'Invalid moderation status'; end if;
  insert into public.p2u_community_moderation(slip_id,status,reason,created_by,updated_by)
  values(clean_id,clean_status,left(coalesce(p_reason,''),500),auth.uid(),auth.uid())
  on conflict(slip_id) do update set status=excluded.status,reason=excluded.reason,updated_at=now(),updated_by=auth.uid()
  returning * into after_row;
  perform public.p2u_write_admin_audit('community.'||clean_status,'community_slip',clean_id,to_jsonb(before_row),to_jsonb(after_row),'{}'::jsonb);
  return to_jsonb(after_row);
end;
$$;
revoke all on function public.p2u_admin_moderate_community(text,text,text) from public;
grant execute on function public.p2u_admin_moderate_community(text,text,text) to authenticated;

create or replace function public.p2u_admin_set_deletion_status(
  p_request_id bigint,
  p_status text
) returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare clean_status text := lower(trim(coalesce(p_status,'')));
declare before_row public.p2u_account_deletion_requests%rowtype;
declare after_row public.p2u_account_deletion_requests%rowtype;
begin
  if not public.p2u_has_admin_role(array['owner','admin']) then
    raise exception 'Admin role required' using errcode='42501';
  end if;
  if clean_status not in ('pending','processing','completed','cancelled') then raise exception 'Invalid deletion status'; end if;
  select * into before_row from public.p2u_account_deletion_requests where id=p_request_id;
  update public.p2u_account_deletion_requests set status=clean_status,
    completed_at=case when clean_status='completed' then now() else null end
  where id=p_request_id returning * into after_row;
  if after_row.id is null then raise exception 'Deletion request not found'; end if;
  perform public.p2u_write_admin_audit('account_deletion.'||clean_status,'deletion_request',p_request_id::text,to_jsonb(before_row),to_jsonb(after_row),'{}'::jsonb);
  return to_jsonb(after_row);
end;
$$;
revoke all on function public.p2u_admin_set_deletion_status(bigint,text) from public;
grant execute on function public.p2u_admin_set_deletion_status(bigint,text) to authenticated;

-- Allow backend admins to review deletion requests. Existing user policies remain intact.
alter table public.p2u_account_deletion_requests enable row level security;
drop policy if exists "Admins read deletion requests" on public.p2u_account_deletion_requests;
create policy "Admins read deletion requests" on public.p2u_account_deletion_requests
for select to authenticated using (public.p2u_has_admin_role(array['owner','admin']));

create or replace function public.p2u_admin_assign_role(
  p_email text,
  p_role text,
  p_active boolean default true
) returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare target_user auth.users%rowtype;
declare clean_role text := lower(trim(coalesce(p_role,'')));
declare before_row public.p2u_admin_roles%rowtype;
declare after_row public.p2u_admin_roles%rowtype;
begin
  if not public.p2u_has_admin_role(array['owner']) then
    raise exception 'Owner role required' using errcode='42501';
  end if;
  if clean_role not in ('owner','admin','moderator') then raise exception 'Invalid role'; end if;
  select * into target_user from auth.users where lower(email)=lower(trim(p_email)) limit 1;
  if target_user.id is null then raise exception 'No account found for that email'; end if;
  select * into before_row from public.p2u_admin_roles where user_id=target_user.id;
  if target_user.id = auth.uid() and (clean_role <> 'owner' or coalesce(p_active,true) = false) then
    raise exception 'You cannot demote or deactivate your own owner account from the browser console';
  end if;
  if before_row.role = 'owner' and before_row.active = true and (clean_role <> 'owner' or coalesce(p_active,true) = false)
     and (select count(*) from public.p2u_admin_roles where role='owner' and active=true) <= 1 then
    raise exception 'At least one active owner must remain';
  end if;
  insert into public.p2u_admin_roles(user_id,role,active,created_by,updated_by)
  values(target_user.id,clean_role,coalesce(p_active,true),auth.uid(),auth.uid())
  on conflict(user_id) do update set role=excluded.role,active=excluded.active,updated_at=now(),updated_by=auth.uid()
  returning * into after_row;
  perform public.p2u_write_admin_audit('role.assign','admin_role',target_user.id::text,to_jsonb(before_row),to_jsonb(after_row),jsonb_build_object('email',target_user.email));
  return jsonb_build_object('user_id',after_row.user_id,'email',target_user.email,'role',after_row.role,'active',after_row.active,'updated_at',after_row.updated_at);
end;
$$;
revoke all on function public.p2u_admin_assign_role(text,text,boolean) from public;
grant execute on function public.p2u_admin_assign_role(text,text,boolean) to authenticated;

-- Bootstrap the first owner. Replace the email before running this script.
do $$
declare owner_email text := 'YOUR_ACCOUNT_EMAIL@example.com';
declare owner_id uuid;
begin
  if owner_email = 'YOUR_ACCOUNT_EMAIL@example.com' then
    raise exception 'Replace YOUR_ACCOUNT_EMAIL@example.com with the signed-in Predict2U account email before running v181 setup.';
  end if;
  select id into owner_id from auth.users where lower(email)=lower(owner_email) limit 1;
  if owner_id is null then
    raise exception 'No existing Supabase Auth user found for %', owner_email;
  end if;
  insert into public.p2u_admin_roles(user_id,role,active,created_by,updated_by)
  values(owner_id,'owner',true,owner_id,owner_id)
  on conflict(user_id) do update set role='owner',active=true,updated_at=now(),updated_by=owner_id;
end $$;

commit;
